golang/dep

CONTRIBUTING.md
* link to open issues within dep
* fix link to pull request help on GitHub
[ci skip]
=> minor updates to contributing.md

context.go, main.go
Also adding a `\n` to the error message just in case.
Closes https://github.com/golang/dep/issues/125
@jessfraz I hope I can just open the PR here right? Let me know if I need to change anything!
=> Changing logic to get the context after we check for --help

ensure.go
I found a minor typo in comment.
Please review and merge it if ok.
Thanks.
=> Fix minor typo

cmd/dep/init.go
=> Remove cute error message

cmd/dep/ensure_test.go, cmd/dep/init_test.go, cmd/dep/remove_test.go, cmd/dep/status_test.go, context_test.go, project_test.go, test/test.go, txn_writer_test.go
TestgoData has been renamed to Helper and Testgo to NewHelper.
=> rename testgo to Helper

context.go, context_test.go
Cleans up ascending lock file bug and adds relative path handling to Ctx.LoadProject.  Adds numerous unit tests to same.  Supercedes PR #200
=> Issues 198 and 201

cmd/dep/main.go
Allow the user to use "-h" or "help" before a command name to print it's usage.
Closes #211
=> improve support for printing command usage

cmd/dep/init.go, cmd/dep/init_test.go
This seems to be all that's needed for #226
=> populate vendor directory when running int

cmd/dep/init.go, context.go, context_test.go
=> case-insensitive GOPATH

test/test.go
Currently when a test is failed by the helper, the test doesn't print enough information to identify the correct line in the failed test. Since we were already using `pkg/errors`, which provides very nice stack trace functionality, I updated the test helper to take full advantage of it.
Here's an example test that will fail:
```go
func TestStuff(t *testing.T) {
h := test.NewHelper(t)
defer h.Cleanup()
h.Must(errors.New("derp"))
}
```
Here's the current output. Note that the file and line number of the failure is in the test helper, not the test itself.
```
$ go test -run TestStuff
--- FAIL: TestStuff (0.00s)
test.go:62: derp
FAIL
exit status 1
FAIL	github.com/golang/dep	0.068s
```
Below is the new output. Note that you can now see where the test failed:
```
$ go test -run TestStuff
--- …
```
=> Print the stack trace when the helper fails a test

lock.json, vendor/github.com/sdboyer/gps/cmd_test.go, vendor/github.com/sdboyer/gps/manager_test.go, vendor/github.com/sdboyer/gps/selection.go, vendor/github.com/sdboyer/gps/selection_test.go
GPS v0.14.0 did not check slice length when doing bmi removal. This lead
to an index out of bounds panic. v0.14.1 fixes this issue
=> #274 Bump minimum version of gps required

cmd/dep/integration_test.go, cmd/dep/remove_test.go, cmd/dep/testdata/harness_tests/README.md, cmd/dep/testdata/harness_tests/ensure/empty/case1/testcase.json, cmd/dep/testdata/harness_tests/ensure/empty/case2/testcase.json, cmd/dep/testdata/harness_tests/ensure/override/case1/testcase.json, cmd/dep/testdata/harness_tests/ensure/update/case1/testcase.json, cmd/dep/testdata/harness_tests/init/case1/testcase.json, cmd/dep/testdata/harness_tests/init/case2/testcase.json, cmd/dep/testdata/harness_tests/init/case3/testcase.json, cmd/dep/testdata/harness_tests/init/skip-hidden/testcase.json, cmd/dep/testdata/harness_tests/remove/force/case1/testcase.json, cmd/dep/testdata/harness_tests/remove/specific/case1/testcase.json, cmd/dep/testdata/harness_tests/remove/specific/case2/testcase.json, cmd/dep/testdata/harness_tests/remove/unused/case1/testcase.json, test/integration_testcase.go
Just some small tweaks to the test harness that I think should make the `testcase.json` files a little more immediately intuitive for contributors.
@tro3, have a look?
=> Rename fields and update test harness docs

cmd/dep/integration_test.go, cmd/dep/remove_test.go, cmd/dep/testdata/harness_tests/README.md, test/integration_testcase.go, test/test.go
Put some effort to keep the resulting format a little more human-editable than the default JSON indented output.
=> Adding -update capability for testcase.json

manifest.go, manifest_test.go, project_test.go, testdata/manifest/error1.toml, testdata/manifest/error2.toml, testdata/manifest/golden.toml
=> Changing "Ignores" to "Ignored"

cmd/dep/integration_test.go
With updated gps, these tests now pass
=> Add integration remove tests to Windows

Gopkg.lock, vendor/github.com/sdboyer/gps/cmd.go, vendor/github.com/sdboyer/gps/deduce.go, vendor/github.com/sdboyer/gps/deduce_test.go, vendor/github.com/sdboyer/gps/satisfy.go
Fixes #387 
Should also improve failure output for #216.
=> Update gps to v0.16.1

.travis.yml
going to play around with making it fail so don't merge til I verify
close #486
=> set -e for travis to fail

cmd/dep/ensure.go, cmd/dep/main.go, hack/licenseok/main.go, internal/internal.go, test/test.go
I incorporated my ideas for `Logln`, let me know if that make sense or not. :satisfied:
Fixes #511
=> Replace most of fmt.Fprintln for internal Logf() and Logln()

internal/gps/typed_radix.go
Remove unused, uncovered, code in typed_radix.go.
=> internal/gps: remove unused code

project.go, project_test.go
Fixes #612.
I tested this on the same project where I ran into this earlier and can confirm that this fixed my issue.
=> Add a leading underscore to vendor backup

FAQ.md
=> FAQ entry: How does `dep` handle symlinks

cmd/dep/prune.go, cmd/dep/testdata/harness_tests/prune/without_lock/final/Gopkg.toml, cmd/dep/testdata/harness_tests/prune/without_lock/initial/Gopkg.toml, cmd/dep/testdata/harness_tests/prune/without_lock/testcase.json
I'am not sure about error message, suggestions are welcome.
Fixes #633
=> Fixed panic in prune subcommand if no lock file exists.

FAQ.md
Pursuant to discussion on mailing list https://groups.google.com/forum/#!topic/go-package-management/fp2uBMf6kq4
=> Expand FAQ to include maintainer-ish questions

cmd/dep/integration_test.go, cmd/dep/remove_test.go, internal/test/integration_testcase.go
Fixes #661 
- Removed `testcase.json` rewrite
- Refactored `UpdateGolden` usages
- DRYed up related test code
=> DRY up integration tests; remove 'Cleanup' testcase.json rewrite

txn_writer.go
Documenting more exported members. #672
=> Document txn_writer.go

internal/fs/fs_test.go
Updates #632
setupInaccessibleDir returns an error which must be checked by the
caller, which always invoked t.Fatal on error.
This change refactors setupInaccessibleDir to call t.Fatal internally
and handle any clean up if necessary.
=> internal/fs: clean up setupInaccessibleDir helper

cmd/dep/glide_importer_test.go
=> Always set a source manager in the glide tests

FAQ.md
Added a FAQ about how to test changes to dependencies.
Also, reorder the FAQs to group related questions.
Ensure that FAQ grouping actually makes sense.
=> Add a FAQ about how to contribute to dependencies

manifest.go, manifest_test.go, testdata/manifest/error3.toml
Small enhancement to check for multiple overrides for the same project.
=> Added check for multiple overrides in manifest files.

cmd/dep/testdata/harness_tests/ensure/empty/case1/final/Gopkg.toml, cmd/dep/testdata/harness_tests/ensure/override/case1/final/Gopkg.toml, docs/Gopkg.toml.md, testdata/txn_writer/expected_manifest.toml, txn_writer.go
This is a PR for fix an open issue.
The new file GOPKG_TOML_EXAMPLE.md. The name is horrible and should get some more thought but the format of what is in there should be reviewed.
The previous style had two sections of information about "metadata". I added them both labeling them as 1) and 2). I would imagine that information should be consolidated by someone more knowledgable about it.
fixes #722
=> Gopk toml cleanup

internal/gps/constraints.go
=> Removed unused ProjectConstraints.merge()

FAQ.md
I did not modify any questions, just changed the order of the questions and grouped them.
=> Group FAQ by topic

FAQ.md
Refer: https://github.com/golang/dep/pull/736#discussion_r121441871
=> FAQ: Correct semver range example

internal/feedback/feedback.go
My manual merge for #833 was bad. It only included the first commit, which was later force pushed over with more commits. This reverts commit 8e7079502ef6429f3355c2017f282cdeb1483d1e, reversing changes made to 88277ade9ad704dd7be6079df0ccd77abc3d1594.
I wonder if this will work? 🤔
=> Revert "Merge pull request #833 from otoolec/feedback"

FAQ.md
There is confusion on how to configure git to allow dep to work with private repositories. This FAQ change provides hopefully clear instructions on how to do that.
Spelling, language, grammar, and whether or not the steps described actually work.
=> FAQ: Added instructions on configuring git authentication.

FAQ.md
Fix an earlier merge, improving grammar and formatting.
The stupid.
=> FAQ: Grammar and formatting fixes

cmd/dep/status.go, cmd/dep/status_test.go
Fixes a crash when running dep -dot
fixes #669
=> Fix crash when running dep -dot

README.md
This fixes README link to the FAQ.
Typos.
=> Fixed the link to FAQ

README.md
Some words for the readme as requested for 855
no sharp edges here. 
Nope 👍 
#855
=> Document semver ranges in the README

README.md
Fixes doc link in README.md to point to the correct location for `docs/Gopkg.toml.md`.
=> Fix link to docs/Gopkg.toml in README.md

cmd/dep/godep_importer.go, cmd/dep/godep_importer_test.go, cmd/dep/status.go, internal/feedback/feedback.go, manifest.go, project.go
**NOTE:** The commits in this PR follow [semantic commit messages](http://karma-runner.github.io/0.13/dev/git-commit-msg.html) to see if it would help us in better managing the changelog and history navigation.
These are small refactoring of the changes introduced by me and some I came across. Most of them are coding style related, adding comments, grouping declarations and correcting error message format.
Correctness of the style.
No.
None.
=> Refactor multiple packages

README.md
=> Add Homebrew

docs/FAQ.md
FAQ addition: How do I make `dep` resolve dependencies from my `GOPATH`?
Or maybe we can rephrase and answer it in a different way?
=> FAQ: resolving dependencies from GOPATH

CONTRIBUTING.md
I always feel awful when multiple people work on the same issue without realizing it. Let's help avoid that by encouraging contributors to leave a comment on issues that they intend to work on.
=> Comment on issues before starting work

.github/CODEOWNERS
Adds testdata/{vndr,govend} in CODEOWNERS.
=> add testdata/{vndr,govend} in CODEOWNERS

cmd/dep/status.go, internal/gps/source.go, internal/gps/source_manager.go, internal/gps/vcs_source.go
Following up with more error cleanup from #1102
=> cleanup errors

internal/gps/source.go
I have the exactly same problem as the comments, and sadly it takes me 1 day to get here.
=> fix: retry after HasLatestLocally **success**

.travis.yml
When i move licence check to bash script. I forget to add it to ci. 
Are there any  other checks missed or needed.
=> Add validate-licence to ci

internal/gps/source_manager.go
Corrects `DeduceProjectRoot` name in comment.
=> docs(gps): DeduceRootProject -> DeduceProjectRoot

.codeclimate.yml
Cuz we are fine with TODOs and FIXMEs.
=> codeclimate: disable fixme

internal/gps/example.go
=> docs(gps): add docs in gps example

hack/build-all.bash
=> Modify build-all.bash script to work on macOS.

cmd/dep/main.go, internal/gps/deduce.go, internal/gps/paths/paths.go, internal/gps/vcs_repo.go, project.go
super minor enhancements/documentation as i was reading through `dep init` :)
=> minor enhancements for dep init

.travis.yml
There are issues running the tests on Xcode8.3 or greater on TravisCI. This PR uses the previous default image.
=> Use Xcode7.3 Travis image

README.md
It adds go report card badge to the readme file.
fixes #1426
=> Added goreportcard badge to readme file.

.travis.yml, hack/build-all.bash
Adds support for more platform
fixes #1418
=> [WIP] Adds support for freebsd and 386 arch

docs/FAQ.md
Fixes example .netrc file.
It works with the reviewer's environment or not
No
N/A
=> fix .netrc example

docs/FAQ.md
=> Correct `.username` to `.example`

docs/Gopkg.toml.md
Correct the metadata example in Gopkg.toml.md
Changed example.
No.
fixes #1513
=> docs: correct the metadata example in Gopkg.toml.md

cmd/dep/main.go, cmd/dep/prune.go
To prevent scripts from breaking after the 0.4 release.
Are the messages clear or can we improve them?
=> Add no-op prune command

CHANGELOG.md
This PR adds a bunch of links to old changelog entries where we only had PR #s.
=> update changelog with links

docs/installation.md
Document how to install dep from source and have the version built into the compiled binary.
Please run it and try for yourself. Note that if you develop dep, and you are on a detached head or have a dirty state, you will need to checkout master first in order for `go get` to work.
Nope.
Closes #1630.
=> Document how to install dep from source

cmd/dep/ensure_test.go, cmd/dep/gopath_scanner_test.go, cmd/dep/prune.go, cmd/dep/status.go, cmd/dep/status_test.go, gps/_testdata/src/relimport/dotdot/a.go, gps/deduce.go, gps/filesystem_test.go, gps/solve_basic_test.go, gps/solve_bimodal_test.go, hack/licenseok/main.go, internal/importers/base/importer.go, internal/test/integration/testproj.go, internal/test/test.go, manifest.go, manifest_test.go
Cleanup code
- removed unused import-aliases
- errors must start with non uppercased letter
Don't think so 🙂
Nothing, just cleanup code
___
- removed unused import-aliases
- errors must start with non uppercased letter
- preallocated slices
=> [FIX] Cleanup code

CONTRIBUTING.md, website/package.json
This change documents contributing to the docs and adds some dev dependencies in package.json to install all the necessary components required by the site to run. More details about those dependencies could be found at https://github.com/facebook/Docusaurus/blob/master/admin/local-third-party-project-testing.md#clowntown.
The wordings in the docs and changes to package.json.
No.
None.
=> docs: Document website local setup

website/package-lock.json
Lock the docusaurus packages because lock files is good for you.
=> Lock Docusaurus npm packages

gps/manifest.go
Documentation-only fix. Has to be fixed because it cannot be unseen ! :scream_cat:
=> typo: Fix method name in comment

cmd/dep/main.go
For example, in order to obtain the memory profile
at the end of the program, run:
$ dep -memprofile=profile.out
Then use the pprof tool to analyze the output:
$ go tool pprof profile.out
=> Add profiling flags

install.sh
=> Added file extension to windows install 

.travis.yml, website/siteConfig.js
Enables algolia search and adds a travisCI build stage to deploy website automatically on master branch only.
According to [algolia-docs](https://www.algolia.com/doc/guides/security/api-keys/?language=go#search-only-api-key), search-only api key is safe to use in front-end code in production.
NOTE: This requires a few environment variables in travisCI settings: `GITHUB_EMAIL`, `GITHUB_USER` and `GITHUB_TOKEN`.
Refer:
* https://docs.travis-ci.com/user/deployment/script/ for script deployment..
* https://docusaurus.io/docs/en/publishing.html#using-circle-ci for the deployment instructions.
to understand the changes.
Should the algolia api key be used from environment variable to make it easy to change later, if required?
fixes https://github.com/golang/dep/issues/1678
=> Docs search

CHANGELOG.md, Gopkg.lock, Gopkg.toml, vendor/github.com/Masterminds/semver/constraints.go, vendor/github.com/Masterminds/semver/parse.go
Update our dependency on Masterminds/semver to follow upstream again now that [Masterminds/semver#67](https://github.com/Masterminds/semver/pull/67) is merged.
=> Bump github.com/Masterminds/semver

docs/FAQ.md
Fix a typo in the FAQ
"dependecy" -> "dependency"
n/a
n/a
n/a
=> Fix a typo in the FAQ 

docs/FAQ.md, docs/ensure-mechanics.md
After reading the documentation I was still unclear on how `dep ensure -update` handles packages that are imported and don't have a `[[Constraint]]` in `Gopkg.toml`. I reached out to @carolynvs on the Gopher's [`#vendor` channel](https://gophers.slack.com/archives/C0M5YP9LN/p1518203250000537) and she [clarified the behavior for me](https://gophers.slack.com/archives/C0M5YP9LN/p1518203296000665) (thanks again!).
@carolynvs recommended I add an FAQ; this is that FAQ. I also corrected related language in the table describing `dep ensure -update`'s behavior.
Make sure the grammar/tone match the rest of the docs.
I still need to add a link in the TOC to my new section, I don't know how to do that, though :grimacing:. Help would be appreciated.
N/A
=> Clarify dep ensure -update behavior for imports.

CONTRIBUTING.md
Adds the Gophers Slack #vendor channel as a general question resource.
Should we check with the admins of Gophers Slack before doing this?
Nope!
N/A
=> Add Gophers Slack vendor channel as resource.

docs/installation.md
The community repo package is preferred to AUR packages.
Nothing.
No.
None.
=> Updated Arch installation instructions.

docs/new-project.md
Clarify that a go file has to be created before dependencies can be added,
to avoid running into the error "no dirs contained any Go code".
Clarifying the documentation for new project setup to avoid running into the error message "no dirs contained any Go code".
It is a minor docs change but the reviewer can check that the new formulation looks good.
No
No issue created for this docs change.
=> Clarify initial setup steps in new-project.md

gps/vcs_source.go
Fix the way hg is invoked so that user extensions don't get to modify command
output in such a way that the rest of the code doesn't recognize it.
In particular, since commands use the "--debug" flag, they are very sensitive to additional logging happening at extension load time.
My working assumption is that we want the mercurial interactions to be as vanilla as possible. If that's not the case, that might be a bigger issue.
=> gps: prevent hg extensions from interfering

cmd/dep/main.go
Fixes https://github.com/golang/dep/issues/1856
See the attached issue description. Most of this PR is moving code around so that we can re-use the usage() function in the flag parser.
=> main.go: fix printing of 'dep -h'

docs/the-solver.md
=> Add wikipedia link for CDCL in documentation

gps/solve_test.go
Signed-off-by: Iskander Sharipov <quasilyte@gmail.com>
=> gps: simplify boolean expression

CONTRIBUTING.md, cmd/dep/testdata/harness_tests/status/case1/table/stdout.txt, cmd/dep/testdata/harness_tests/status/old_constraints/stdout.txt, cmd/dep/testdata/harness_tests/status/override_constraint/stdout.txt, cmd/dep/testdata/harness_tests/status/revision_constraint/stdout.txt, docs/Gopkg.toml.md, docs/env-vars.md, website/blog/2018-07-25-announce-v0.5.0.md, website/static/css/custom.css
Signed-off-by: Xiang Dai <764524258@qq.com>
=> Delete all duplicate empty blanks

README.md
Added Debian installation instructions since it's available there and is helpful to know about the option.
Just run the command, nothing much added just the README.md addition.
It just provides one more way to get go dep working in a dev environment.
This will also close the [pull request, which does not pass due to CLA](https://github.com/golang/dep/pull/1978).
=> Added instruction for installing to Ubuntu by apt.

.travis.yml, Gopkg.lock, gps/pkgtree/pkgtree.go, gps/pkgtree/pkgtree_test.go, vendor/github.com/google/go-cmp/LICENSE, vendor/github.com/google/go-cmp/cmp/compare.go, vendor/github.com/google/go-cmp/cmp/internal/diff/debug_disable.go, vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go, vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go, vendor/github.com/google/go-cmp/cmp/internal/function/func.go, vendor/github.com/google/go-cmp/cmp/internal/value/format.go, vendor/github.com/google/go-cmp/cmp/internal/value/sort.go, vendor/github.com/google/go-cmp/cmp/options.go, vendor/github.com/google/go-cmp/cmp/path.go, vendor/github.com/google/go-cmp/cmp/reporter.go, vendor/github.com/google/go-cmp/cmp/unsafe_panic.go, vendor/github.com/google/go-cmp/cmp/unsafe_reflect.go
Apparently Go 1.12 broke all of the tests.
=> travis.yml: update to Go 1.12

gps/solver.go
https://github.com/golang/dep/pull/2058 resubmitted against master, so we can get tests passing and merge it.
=> better information for panic on nil version

gps/source.go
Originally submitted by Iskander Sharipov, who has signed the CLA, as
https://github.com/golang/dep/pull/2029; submitting under my name to
get past the CLA bot.
=> gps: replace redundant lambda wrapper with method value

docs/daily-dep.md
Originally submitted by George Gabolaev &lt;gabolaev98@gmail.com&gt; as
PR #2017. George has signed the CLA.
=> daily-dep.md: add missing quotes

docs/migrating.md
Originally submitted by Matthew Cale as #2009. Submitting under my
commit to work around CLA issues. Matthew has signed the CLA.
Fixes #2009.
=> docs: added missing word

README.md, docs/installation.md
=> README.md: update installation instructions

CHANGELOG.md
=> CHANGELOG: prepare for 0.5.3 release

README.md
=> README: add note about seeking funding
