golang/dep

main.go

The local variables `command` shadow the `command` type declaration unintentionally.
This might give confusion to maintainers so I rename the local variable name of `command` to `cmd`.

Rename the local variable name of `command` to `cmd`

---

.travis.yml
status_test.go

`master` branch was failing the travis test for a while because of `status_test.go` format error by `gofmt`. just formatted.
And mainly, this PR for `|&` pipe is despite syntax error on travis osx vm, but test passes. (maybe due to differences `bash` version?)
See https://ember-canary.travis-ci.org/golang/dep/jobs/195026617#L77-L79
This will be a problem in the future, so fixed it together.
This pull request will pass travis test, but conflicted #143.
So if merge #143 first, I will rebase and fix pull request to only fixed `.travis.yml`.

fix '|&' pipe on travis osx vm

---

main_test.go
status_test.go

Hey all!
It's been a long time coming and thanks for this project!
I came across https://github.com/golang/dep/issues/41 and hope to contribute a small test snippet as my first PR :)
Increased main.go coverage from 12.8% to 21.8%
- Added test for `project.makeParams()`
- Added an extra test for `findProjectRoot()`

Added more tests to main_test.go

---

manifest.go

Avoid elses everywhere in the code base. More indentation makes the code harder to read.

avoid elses as much as possible

---

.travis.yml

These wait times are unbearable. 
Combine that with the unreliability of appveyor, and CI is just borked right now. Disabling OSX, for now.

Disable OSX on travis

---

dep_test.go

As far as I can see, It seeks git.exe call fork(2) to do something about ls-remote or git-remote-http on Windows. But it often quit without waiting the child process. So the git.exe hold the handle of directory which should be removed. This occured while removing temporary directory in tg.cleanup. I don't know how to fix this git process. For example:
```diff
diff --git a/dep_test.go b/dep_test.go
index ecec35f..9f518be 100644
--- a/dep_test.go
+++ b/dep_test.go
@@ -16,6 +16,7 @@ import (
"runtime"
"strings"
"testing"
+	"time"
)
var (
@@ -483,8 +484,16 @@ func (tg *testgoData) cleanup() {
tg.check(os.RemoveAll(path))
}
if tg.tempdir != "" {
-		exec.Command(`taskkill`, `/F`, `/IM`, `git.exe`).Run()
-		tg.check(os.RemoveAll(tg.tempdir))
+		if runtime.GOOS == "windows" {
+			for {
+				if …
```

fix error on AppVeyor

---

analyzer.go
ensure_test.go
init_test.go
remove_test.go

The change also includes minor style fixes for some comments.

rename hoard to dep

---

ensure.go

Fix for #162.
ctx.loadProject() allows for the lock file to not exist, but we don't take that into account in ensure.Run when specifying projects or overrides.

dep ensure: fix nil* when lock not exists

---

ensure.go
hash_in.go
init.go
main.go
remove.go
status.go

In this commit, I altered the `command` interface so `Run` also accepts a `*ctx` and we no longer have to keep it global.
Tests are all passing and since `depContext` has been removed, if any other function needed the context it would not compile, so I don't think we should be worried anything has been broken by this.
Also, it solves https://github.com/golang/dep/issues/169. It was already solved by @vanadium23 here (https://github.com/golang/dep/pull/172), but since it's not merged yet and I needed the context there I already made the change. Since he fixed the issue, I think we should wait for his PR to be merged and rebase against master when it is :)

Deglobalize dep context

---

context.go

I'd like to put `Close` function on above the line. Just like this;
https://github.com/golang/dep/blob/master/context.go#L82

More readable

---

context.go
main_test.go

On Windows, I use slash separated GOPATH like `C:/dev/go` because backslash often makes wrong.

handle slashed GOPATH

---

cmd/dep/status.go

use fmt.Fprintln instead of fmt.Fprintf

---

test/test.go

sorry for the nit pull-request. I just noticed that t.Skipf is misused while reading the code.

Fix misuse of t.Skipf

---

README.md

Currently, not tested in OSX environment. Please re-add when enable OSX test.
Also, Most newcomers don't know about -u.
https://twitter.com/rakyll/status/804426773446332416

remove osx from ci badge and add '-u' flag for install

---

context.go

Hi
I've changed the returning value of ctx.loadProject when error because the first returning value is useless.

Change returning value of ctx.loadProject when error

---

cmd/dep/init.go

Adding new dependency logging 

---

cmd/dep/status.go

JSON output

---

cmd/dep/ensure_test.go
test/test.go

For #228 
I added a helper for getting the latest tag, and used that in place of a fixed version for logrus in the test.

Fixed TestEnsureEmptyRepoNoArgs

---

cmd/dep/ensure.go
fs.go
fs_test.go

#234 
If the vendor directory existed & was empty, but the current lockfile matched the solution, nothing would be written to vendor. This adds a check to see if the directory is empty and forces the write in that case.

ensure should write vendor when the directory is empty

---

cmd/dep/init_test.go
cmd/dep/remove_test.go
cmd/dep/testdata/init/bar.input.go
cmd/dep/testdata/init/lock.golden.json
cmd/dep/testdata/init/manifest.golden.json
cmd/dep/testdata/init/thing.input.go
cmd/dep/testdata/remove/lock1.golden.json
cmd/dep/testdata/remove/main.input.go
cmd/dep/testdata/remove/manifest.input.json
cmd/dep/testdata/remove/manifest0.golden.json
cmd/dep/testdata/remove/manifest1.golden.json

Moving remaining integration tests to golden file pattern. For some reason, the remove_test.go is now passing on my PC, despite nothing being commented out or skipped. We'll see if Appveyor believes the same.

Golden file pattern for integration tests, reduced commits

---

.gitattributes

Fixes #243.
This overrides a user's EOL settings for the `testdata/` directories, forcing all files under them to use LF. I've tested this out with Git for Windows by doing the following:
1. Clone and cd into the repo
1. Turn on AutoCRLF for the repo (so I don't muck up my entire machine)
```
git config core.autocrlf true
```
1. Reset the cached files to apply the new line ending scheme
```
git rm --cached -r .
git reset --hard
```
1. Open the project in a text editor which can tell you the line ending types in use (I picked Atom).
1. Open some go files and make sure that AutoCRLF has applied windows style line endings.
1. Open `/testdata/analyzer/manifest.json` and verify that it uses LF, not CRLF.
1. Open `/cmd/dep/testdata/ensure/bare_lcok.golden.json` and verify that it uses LF as …

Prevent problems comparing golden files on Windows

---

hack/validate-vendor.bash

Looks like this repo was renamed from `nest` to `dep`, so here's a tiny patch that updates the vendor validator to point to the right repo name. This isn't strictly necessary (GitHub sends a 301 for /golang/nest), just figured it'd reduce confusion.

hack: update repo name

---

cmd/dep/init.go

Fixes one of the aspects of https://github.com/golang/dep/issues/270

Adding a newline to the end of solve err

---

cmd/dep/main.go

Dep's extended help text is great, but not obvious to find. I spent a little time doing `dep --help`, `dep -h`, `dep help`, looking for more info. This change adds a small note to the usage text that points the user to `dep help subcommand`. I took the prose from the `go` command's usage text, so if you disagree with the wording, you are literally a heretic.
The usage changes from
```
▶ dep                                                           
Usage: dep <command>
Commands:
init    Initialize a new project with manifest and lock files
status  Report the status of the project's dependencies
ensure  Ensure a dependency is safely vendored in the project
remove  Remove a dependency from the project
```
to...
```
▶ dep                                                           
Usage: dep …
```

Add a note about extended help being available

---

cmd/dep/ensure.go
cmd/dep/init.go
cmd/dep/remove.go
cmd/dep/testdata/harness_tests/ensure/update/case2/final/lock.json
cmd/dep/testdata/harness_tests/ensure/update/case2/final/manifest.json
cmd/dep/testdata/harness_tests/ensure/update/case2/initial/lock.json
cmd/dep/testdata/harness_tests/ensure/update/case2/initial/main.go
cmd/dep/testdata/harness_tests/ensure/update/case2/initial/manifest.json
cmd/dep/testdata/harness_tests/ensure/update/case2/testcase.json
fs.go
lock.go
lock_test.go
manifest_test.go
test/test.go
test_project_context_test.go
testdata/txn_writer/expected_diff_output.txt
testdata/txn_writer/original_lock.json
testdata/txn_writer/updated_lock.json
txn_writer.go
txn_writer_test.go

This fixes #145.
When I first looked at this, turning on `-v` by default when `-n` is present, seemed like an easy win. However the verbose output from the `gps` solver wasn't really what I was looking for in a dry-run, I wanted to know what ensure would do, not what it evaluated. So I added output which clearly shows what will be written to the filesystem when the command is run without `-n`.
```
$ dep ensure -n
Would have written the following manifest.json:
{
"dependencies": {
"github.com/Masterminds/semver": {
"branch": "2.x"
},
"github.com/Masterminds/vcs": {
"version": "^1.8.0"
},
"github.com/pkg/errors": {
"version": ">=0.8.0, <1.0.0"
},
"github.com/sdboyer/gps": {
"branch": "master"
}
}
}
Would have written the following lock.json:
{
"memo": …
```

Respect dry run flag during dep ensure

---

lock.go
test_project_context_test.go
testdata/txn_writer/expected_diff_output.txt
testdata/txn_writer/updated_lock.json
txn_writer.go

I wasn't sure if we needed more discussion about #308 (renaming repo to source in the lock file)? It would be a breaking change.

Rename the lock field "repo" to "source"

---

cmd/dep/init.go

While getting familiar with the dep source I came across this unused function that seems to have been left behind after the refactor in 0acfd38 .

Remove unused function writeFile from init.go

---

cmd/dep/ensure.go
cmd/dep/init.go
cmd/dep/remove.go
testdata/txn_writer/expected_diff_output.txt
txn_writer.go
txn_writer_test.go

I wasn't taking forcevendor into account properly when the diffs were the same (which is exactly what that flag was for...) 😞 
This fixes my misunderstanding about when lock and newlock should be set in the SafeWriter tests.  Previously, I thought I should only pass in newlock when the lock had changed, or was brand new, when actually it should be passed anytime there was an existing lock file. Due to the bad test, it was missing that a bare ensure with an existing lock file (and no vendor) should result in vendor being written.
This fixes #323.

Write vendor, regardless of lock, if force is true

---

cmd/dep/ensure.go
cmd/dep/init.go
cmd/dep/remove.go
cmd/dep/status.go
context.go
lock.go
manifest.go
project.go
test_project_context_test.go
txn_writer.go

Found another that snuck past my initial sweep for calls to `test.Helper.Must` without a stacktrace.

Wrap error so the test prints the stack trace

---

cmd/dep/main.go

Not sure if it's worth having an `examples` slice like this, or just hardcoding them. Would save a lot of lines. Depends if we want to make examples a first class citizen of the command object I guess. Ensure's current `dep ensure -examples` is rather hidden away atm, so we should maybe go that way. Anyway... This PR gives us:
```
▶ dep help            
dep is a tool for managing dependencies for Go projects
Usage: dep <command>
Commands:
init    Initialize a new project with manifest and lock files
status  Report the status of the project's dependencies
ensure  Ensure a dependency is safely vendored in the project
remove  Remove a dependency from the project
Examples:
dep init                          set up a new project
dep ensure                        install the project's …
```

Add examples to the main usage output

---

cmd/dep/main.go
cmd/dep/prune.go
txn_writer.go

Part of #120 
This changes adds a basic pruning strategy for the vendor directory.  Before this changes, vendoring with `dep` resulting in a +4m loc change to [weaveworks/cortex](https://github.com/weaveworks/cortex) vs `gvt`, after running prune its -1.3m.
There is a bunch left to do, I thought it best to open this PR and get feedback early.  If you like this approach I will open a PR on sdboyer/gps for the `PackageDeps` method.
We could also potentially add code to remove non-go files and `*_test.go` from vendoring - currently I use this in my makefile:
find vendor -type f ! -name '*.go' -a ! -name '*.s' -a ! -name '*.h' -a ! -name '*.proto' -a ! -name LICENSE | xargs -L 10 rm
find vendor -type f -name '*_test.go' | xargs -L 10 rm

Add dep prune subcommand

---

cmd/dep/integration_test.go
cmd/dep/status.go
cmd/dep/testdata/harness_tests/ensure/update/case1/testcase.json
cmd/dep/testdata/harness_tests/ensure/update/case2/testcase.json
cmd/dep/testdata/harness_tests/status/case1/final/Gopkg.lock
cmd/dep/testdata/harness_tests/status/case1/final/Gopkg.toml
cmd/dep/testdata/harness_tests/status/case1/initial/Gopkg.lock
cmd/dep/testdata/harness_tests/status/case1/initial/Gopkg.toml
cmd/dep/testdata/harness_tests/status/case1/initial/main.go
cmd/dep/testdata/harness_tests/status/case1/testcase.json
test/test.go

* Fixes #384 which was introduced when we bumped gps to v0.16.
* Adds integration test for `dep status`
* Fixes problem with test harness where the test would pass when one of the commands fails. Which found some other tests that were actually failing, so I fixed those too. This is in this PR because without it, the "failing" test I added for status incorrectly passes. 😄 
Let me know if this needs to be split into 2 PRs.

Set a ProjectAnalyzer when solving for dep status

---

hack/validate-vendor.bash

This removes `TRAVIS_BRANCH` so the script works the same locally as in Travis. Also fixes "build dep" to run ensure since the command code was moved to `cmd/dep`.

hack/validate-vendor.bash: fix build dep & script without TRAVIS_BRANCH

---

.travis.yml
test/integration_testcase.go
txn_writer.go

[`staticcheck`](https://github.com/dominikh/go-tools/tree/master/cmd/staticcheck) is an awesome static analyzer that's described by the author as "`go vet` on steroids". IMHO it should be a part of every Go project. It's like having an extra full-time bug-finding engineer on the team. [The list of bugs it can catch is quite extensive](https://github.com/dominikh/go-tools/tree/master/cmd/staticcheck#checks).
The good news is: `staticcheck` didn't find any serious bugs in `dep`. :tada: Well done, guys! Nice coding 😄
The minor issues it did find are...
1. a missing `err` check
1. use of [a deprecated stdlib func](https://codereview.appspot.com/5712045)
1. an ineffective, but innocent `break` statement that was intended as a no-op
These are small issues, but I think there's a clear benefit in …

Scrub clean in staticcheck. Add staticcheck to .travis.yml file

---

cmd/dep/testdata/harness_tests/ensure/empty/case3/README.md
cmd/dep/testdata/harness_tests/ensure/empty/case3/final/Gopkg.lock
cmd/dep/testdata/harness_tests/ensure/empty/case3/final/Gopkg.toml
cmd/dep/testdata/harness_tests/ensure/empty/case3/initial/Gopkg.lock
cmd/dep/testdata/harness_tests/ensure/empty/case3/initial/Gopkg.toml
cmd/dep/testdata/harness_tests/ensure/empty/case3/initial/main.go
cmd/dep/testdata/harness_tests/ensure/empty/case3/initial/samples/samples.go
cmd/dep/testdata/harness_tests/ensure/empty/case3/testcase.json

Validate that packages imported in an ignored package are not included in the manifest or lock.

Add test case for ignored packages

---

lock.go
txn_writer.go
txn_writer_test.go

I've updated dep to use LockDiff from gps. I've also simplified the LockDiff test in dep to only focus on formatting the diff, now that the diff implementation lives in gps and deploy only implements formatting.
Fixes #312

Use LockDiff from gps

---

.travis.yml
cmd/dep/status.go
test/integration_testproj.go

[`gosimple`](https://github.com/dominikh/go-tools/tree/master/cmd/gosimple) is a neat little code linter from the author of [`staticcheck`](https://github.com/dominikh/go-tools/tree/master/cmd/staticcheck). It catches code quality issues like the following:
```go
// should be if boolVar
if boolVar == true {}
// should be time.Since(x)               
time.Now().Sub(x)
// should be return err                        
if err != nil {
return err
}
return nil 
```
[The full list of checks is available here](https://github.com/dominikh/go-tools/tree/master/cmd/gosimple#checks).
It only found one issue, which is _very_ good for a project this size. Kudos to all the contributors! 💯

Add gosimple linter to .travis.yml. Fix new staticcheck issue.

---

cmd/dep/ensure.go
cmd/dep/init.go
cmd/dep/main.go
cmd/dep/remove.go
internal/internal.go

This lets other internal packages, like [glide import](https://github.com/golang/dep/issues/380#issuecomment-296344734), write verbose messages for debugging.

Move logging functions into internal package

---

.travis.yml
cmd/dep/init.go
context.go
fs.go
internal/fs.go
internal/fs_test.go

The HasPrefix function determines whether a given path is contained in
another, being careful to take into account that "/foo" doesn't contain
"/foobar" and that there are case-sensitive and case-insensitive
fileystems out there.
This addresses issue #296. In the current state it does not really fix
it because it needs support and testing for non-Unix platforms.
Signed-off-by: Marcelo E. Magallon <marcelo.magallon@gmail.com>

Implement a path-aware HasPrefix function

---

txn_writer.go
txn_writer_test.go

Add vendor/.git exists check in SafeWriter.Write

---

cmd/dep/testdata/harness_tests/ensure/empty/case1/final/Gopkg.toml
cmd/dep/testdata/harness_tests/ensure/empty/case2/final/Gopkg.toml
cmd/dep/testdata/harness_tests/ensure/empty/case3/final/Gopkg.toml
cmd/dep/testdata/harness_tests/ensure/override/case1/final/Gopkg.toml
cmd/dep/testdata/harness_tests/init/case1/final/Gopkg.toml
cmd/dep/testdata/harness_tests/init/case2/final/Gopkg.toml
cmd/dep/testdata/harness_tests/init/case3/final/Gopkg.toml
cmd/dep/testdata/harness_tests/init/skip-hidden/final/Gopkg.toml
cmd/dep/testdata/harness_tests/remove/force/case1/final/Gopkg.toml
cmd/dep/testdata/harness_tests/remove/specific/case1/final/Gopkg.toml
cmd/dep/testdata/harness_tests/remove/specific/case2/final/Gopkg.toml
cmd/dep/testdata/harness_tests/remove/unused/case1/final/Gopkg.toml
cmd/dep/testdata/harness_tests/status/case1/final/Gopkg.toml
testdata/txn_writer/expected_manifest.toml
txn_writer.go

This expands the example text we add to `Gopkg.toml` to cover all valid values for the file.
It also changes the behavior of `dep init` to write out the example data unconditionally to the bottom of Gopkg.toml, rather than doing so only if nothing was to populate the manifest.
I'm not sure this latter part is the best idea, but being that there will be precious few situations under which we'd have an empty manifest (once init changes are done, #277), it seems worth being more aggressive about writing out these examples.
We could also add a flag to init that allows the user to suppress writing out the examples.

Expand example Gopkg.toml text; always add on init

---

analyzer.go
analyzer_test.go

Test error conditions:
* Manifest file cannot be read
* Manifest file is invalid
This addresses issue #41.
Signed-off-by: Marcelo E. Magallon <marcelo.magallon@gmail.com>

Improve coverage for DeriveManifestAndLock

---

.codeclimate.yml
.travis.yml
README.md

So it looks like test coverage is only  Ruby, JavaScript, PHP, and Python from: https://docs.codeclimate.com/docs/setting-up-test-coverage
But we could use this for golint, gofmt, etc and then remove those from travis so it's faster and use codecov for coverage?

add codeclimate

---

cmd/dep/init.go
cmd/dep/integration_test.go
cmd/dep/testdata/harness_tests/README.md
cmd/dep/testdata/harness_tests/init/manifest-exists/testcase.json
test/integration_testcase.go
test/integration_testproj.go

@sdboyer new PR for updating the test harness to have verify errors, with the other update work that has happened the error that I was having earlier has now gone 😄

Test harness can now assert if errors have been raised correctly

---

cmd/dep/init.go
cmd/dep/init_test.go
cmd/dep/testdata/harness_tests/ensure/empty/case1/final/Gopkg.lock
cmd/dep/testdata/harness_tests/ensure/empty/case1/final/Gopkg.toml
cmd/dep/testdata/harness_tests/ensure/override/case1/final/Gopkg.toml
cmd/dep/testdata/harness_tests/ensure/pkg-errors/case1/final/Gopkg.lock
cmd/dep/testdata/harness_tests/init/case1/final/Gopkg.lock
cmd/dep/testdata/harness_tests/init/case1/final/Gopkg.toml
cmd/dep/testdata/harness_tests/init/case2/final/Gopkg.lock
cmd/dep/testdata/harness_tests/init/case2/final/Gopkg.toml
cmd/dep/testdata/harness_tests/init/case3/final/Gopkg.lock
cmd/dep/testdata/harness_tests/init/case3/final/Gopkg.toml
cmd/dep/testdata/harness_tests/init/skip-hidden/final/Gopkg.lock
cmd/dep/testdata/harness_tests/init/skip-hidden/final/Gopkg.toml

- Adds assuming project revision to be master when VersionInWorkspace
fails for not on disk projects. Failed projects were being skipped from
manifest before this change.
- Adds running solver once at init. This ensures creating an initial
lock with memo hash in lock file.
Fixes #356 and #149

Implement new spec for init

---

cmd/dep/ensure.go
cmd/dep/init.go
cmd/dep/remove.go
txn_writer.go
txn_writer_test.go

First pass at #491 
Not sure if most correct way to pass back the error in the `NewSafeWriter` function or if I should just be returning the `error` if one happens or I should wrap it.

removing Prepare method in exchange for NewSafeWriter

---

context_test.go

Optional windows symlink testing

---

analyzer_notwindows_test.go
analyzer_test.go
analyzer_windows_test.go

This PR allows `TestAnalyzerDeriveManifestAndLockCannotOpen` to run on Windows.

Add Windows specific function for making a file unreadable during tests.

---

gps/source.go

This addresses #484. It does fix the simple case that I was testing against, which I'm able to reliably repeat locally, though wasn't sure how to make this into an integration test because it relies on git shenanigans.
1. Create go package with a release and push it to github.
```golang
package main
import "fmt"
func main() {
fmt.Println("I'm a dependency!")
}
```
2. Create a go package that imports this dependency and then run `dep init`. This populates the cache with the dependency.
```golang
package main
import _ "github.com/carolynvs/tmp1"
func main () {}
```
```toml
[[dependencies]]
name = "github.com/carolynvs/tmp1"
version = "2.0.2"
```
```toml
[[projects]]
name = "github.com/carolynvs/tmp1"
packages = ["."]
revision = "b3739bbc9944d9f4c82676e6b90ed161f0981351"
version = "2.0.2" …
```

Update cached source before listing packages

---

gps/pkgtree/pkgtree.go
gps/pkgtree/pkgtree_test.go
gps/satisfy.go

Fixes #399 - there was both an underlying bug (`"."` imports weren't discarded appropriately by `PackageTree.ToReachMap()`) and a logging error (certain errors coming back from `*solver.check()` weren't included in trace output).

Dot import handling, improved trace errors

---

test/integration_testcase.go

Logging unexpected errors would help in better failure visibility.

Log stderr for unexpected integration test error

---

gps/source.go

Fixes #144.
I'm not sure how to add a test for this since the tests for `sourceGateway` assume git.

Store version map in cache on success (instead of failure) to retrieve it.

---

manifest.go

This function used to detect if the manifest was empty and should be written with the example text. It is no longer used as of #462.

Remove unused function

---

cmd/dep/ensure.go
cmd/dep/init.go
cmd/dep/prune.go
cmd/dep/remove.go
cmd/dep/status.go
gps/example.go
gps/solve_test.go
gps/solver.go

This change is a simplification with no effect on program behavior.
Originally discussed here: https://github.com/golang/dep/pull/525#discussion_r115111629
The `Trace` field looked like a switch to turn on trace logging, which required a nil validation check on `TraceLogger`. However, nil checking the logger is the actual mechanism that triggers logging internally, and the logger was passed along even if `Trace==false`, so `Trace` was really only a switch to turn on a nil check. All (7) usages set `TraceLogger` to the result of `log.New()` which is never nil, so the validation was not necessary, and omitting it does not otherwise change program behavior.

gps/solver - Remove SolveParameters.Trace

---

cmd/dep/ensure.go
cmd/dep/init.go
cmd/dep/status.go
gps/manager_test.go
test_project_context_test.go

This is a refactor that shouldn't change behavior. It just gets `package main` to use interfaces instead of concrete implementations for `SourceManager`.
The idea here is to make it easier to write tests that mock the source manager's behavior. I have some tests of the status command I'd like to write to get it to support the `required` field.

Use gps.SourceManager instead of *gps.SourceMgr in cmd/dep

---

manifest.go
manifest_test.go

- Use manifest buffer to create a map of TomlTree and find all the
unknown fields in the tree. Raise warnings for unknown fields.
- For "metadata" field, ensure it's of map type, else raise warning.
Fixes #506

Add metadata to manifest & warn on unknown fields

---

fs_test.go

* TestCopyDir: add subdirectory to the test case; extend test to handle
multiple files in different directories.
* Add tests for error conditions in CopyDir: source directory cannot be
read; destination directory cannot be read; files cannot be read.
* Add tests for error conditions in IsRegular.
* Add tests for error conditions in IsDir.
This addresses issue #41.
Signed-off-by: Marcelo E. Magallon <marcelo.magallon@gmail.com>

Improve coverage for fs operations

---

context.go
context_test.go

This should solve #471.
The panic was caused by line 186 trying to get a slice starting at larger index than the path string length:
```go
return filepath.ToSlash(path[len(srcprefix):]), nil
```
But `len(srcprefix)` will be larger than the length of `path` since it will include an additional `filepath.Separator`
I don't like the message honestly, but it's the best I could come up with currently. 😞

Show a clear error message when trying to 'dep init' in $GOPATH/src

---

internal/gps/_testdata/src/dotgodir/foo.go/foo.go
internal/gps/pkgtree/pkgtree.go
internal/gps/pkgtree/pkgtree_test.go

As with the rest of the toolchain, according to @davecheney, we should ignore `_` and `.` prefixed files as well as all directories in `fillPackages` which assumes it's working on a single directory.
Fixes #550

Ignore dot-prefixed files and subdirs when scanning packages

---

.travis.yml

This seems to no longer be necessary.
Added in 871f5938  by @kris-nova, apparently contingent on #296 which has now been closed.

Remove staticcheck exemption

---

cmd/dep/init.go
internal/gps/deduce_test.go
internal/gps/hash_test.go
internal/gps/manager_test.go
internal/gps/pkgtree/pkgtree_test.go
internal/gps/solve_bimodal_test.go
internal/gps/source_test.go
internal/gps/strip_vendor_nonwindows_test.go
internal/gps/strip_vendor_test.go
internal/gps/strip_vendor_windows_test.go
vendor/github.com/Masterminds/semver/constraints_test.go
vendor/github.com/Masterminds/vcs/git.go
vendor/github.com/Masterminds/vcs/git_test.go
vendor/github.com/pelletier/go-toml/marshal_test.go
vendor/github.com/pelletier/go-toml/tomltree_create_test.go
vendor/github.com/pelletier/go-toml/tomltree_write.go

We're not enforcing them in CI yet.
See @sdboyer's comment on
https://github.com/golang/dep/pull/555#issuecomment-300765542
NOTE: This was all done with `gofmt`, I just typed:
```bash
gofmt -w -s -l $(go list ./... | grep -v /vendor/)
```

Fix all gofmt lint errors

---

internal/gps/source.go

This changes proposes a simplification to the async interaction between `getSourceGatewayFor` and `setUpSourceGateway`.
Previously, each call to `setUpSourceGateway` was launched in a new goroutine in every case (while the parent blocked) - it would either do the actual work, or just queue the `srcReturnChans` that its parent was waiting on and then complete.  Now the call to `setUpSourceGateway` is made synchronously, so it either does the actual work and returns normally, or queues its own `srcReturnChans` and waits for a response, but never spawns any goroutines.
Additionally, the `srcReturnChans` were changed from unbuffered to a buffer size of 1, so that the `doReturn` loop can send them all without blocking.

sourceCoordinator source gateway concurrency simplification

---

cmd/dep/init.go
internal/test/test.go
project.go
project_test.go

- Creates backup of vendor directory, if exists with content, at init.
- Adds tests for BackupVendor() function.
- Adds RemoveFile() function to test helper.
Fixes #552

Backup vendor at init

---

fs.go

- IsNonEmptyDir() uses ioutil.ReadDir() which collects all the files in
the directory, sorts and obtains FileInfo structs before returning.
- File.Readdirnames() fetches only the requested number of children and
returns. No extra calls.

Improve IsNonEmptyDir - use File.Readdirnames

---

cmd/dep/init.go
internal/feedback/feedback.go
internal/feedback/feedback_test.go

- Compares manifest, lock and packageTree to separate direct and transitive
dependencies. Based on the constraints, logs them as feedback.
- Creates ConstraintFeedback struct to hold dep constraint data.
- Adds GetUsingFeedback() and GetLockingFeedback() functions to generate
feedback text.
Fixes #503

Add itemized feedback for dep resolution in init

---

internal/gps/hash.go

Remove unused, untested, sortPackageOrErr type.
Coverage of internal/gps improved from 81.6% to 81.9% with this change.

internal/gps: remove unused sortPackageOrErr type

---

txn_writer.go
txn_writer_test.go

SafeWriter.HasVendor was only used in a test context. Unexport
SafeWriter.WriteVendor and use it directly.

dep: remove SafeWriter.HasVendor method

---

cmd/dep/init.go
cmd/dep/testdata/harness_tests/init/case1/final/Gopkg.toml
cmd/dep/testdata/harness_tests/init/case3/final/Gopkg.toml

Attempts to fix #574.
Ran `dep ensure` before I built this locally to get dependencies. It added all of the vendor files and not sure if they should be there.
Also, I wasn't sure if this was better suited being moved into the gps package instead of just in the init.
Thanks,

Don't add unconstrained deps to Manifest on init.

---

internal/test/integration_testproj.go

This makes is easier to quickly scan the test output, without messing up the section header indents.
Here's a sample of how that looks:
```
integration_testproj.go:180: standard error:
Finding dependencies of "github.com/golang/notexist"...
Found 2 dependencies.
Detected glide configuration files...
Loading /private/var/folders/_t/fbw4wf_s42dfqdfjq7shdfm40000gn/T/gotest490168315/src/github.com/golang/notexist/glide.yaml
Loading /private/var/folders/_t/fbw4wf_s42dfqdfjq7shdfm40000gn/T/gotest490168315/src/github.com/golang/notexist/glide.lock
Converting from glide.yaml and glide.lock...
```

Print integration test output on a newline

---

internal/gps/source_test.go

While working on another issue, I noticed that the message was
backwards. Maybe this only bothers me, but it's technically not correct.

Swap expected/got for correct output in vcs_source_test

---

cmd/dep/init.go
cmd/dep/integration_test.go
cmd/dep/remove_test.go
cmd/dep/testdata/init_path_tests/relative_path/final/project_dir/Gopkg.lock
cmd/dep/testdata/init_path_tests/relative_path/final/project_dir/Gopkg.toml
cmd/dep/testdata/init_path_tests/relative_path/initial/project_dir/foo/bar.go
cmd/dep/testdata/init_path_tests/relative_path/initial/project_dir/main.go
cmd/dep/testdata/init_path_tests/relative_path/testcase.json
internal/test/integration_testcase.go
internal/test/integration_testproj.go

Fixes https://github.com/golang/dep/issues/537
Need some help on test cases. The current approach is giving issues as adding tests to `harness_tests/init` cannot find vendor paths. Let me know if there is a better approach to test this feature.

dep init - support relative path 

---

appveyor.yml

Updates #542
Try another way to test all the packages in this project, sans vendor/,
without accidentally swallowing the exit status.

appveyor.yml: fix failure to detect windows build errors

---

internal/gps/deduce.go
internal/gps/maybe_source.go
internal/gps/vcs_source.go
internal/gps/vcs_source_test.go

Fixes #425
```bash
dep-test - master! ❯ dep ensure -v gopkg.in/mgo.v2-unstable
dep: No constraint or alternate source specified for "gopkg.in/mgo.v2-unstable", omitting from manifest
Root project is "scratch/dep-test"
1 transitively valid internal packages
2 external packages imported from 2 projects
(0)   ✓ select (root)
(1)     ? attempt github.com/pkg/errors with 1 pkgs; at least 1 versions to try
(1)         try github.com/pkg/errors@v0.8.0
(1)     ✓ select github.com/pkg/errors@v0.8.0 w/1 pkgs
(2)     ? attempt gopkg.in/mgo.v2-unstable with 1 pkgs; 1 versions to try
(2)         try gopkg.in/mgo.v2-unstable@v2-unstable
(2)     ✓ select gopkg.in/mgo.v2-unstable@v2-unstable w/5 pkgs
✓ found solution with 6 packages from 2 projects
Solver wall times by segment:
b-list-pkgs: 637.471037ms …
```

Add support for -unstable gopkg.in imports

---

cmd/dep/init.go

- Remove "dep:" prefix logs.
- Remove logging gps solution lock constraints, instead enumerate not on disk
projects.

Cleanup init verbose output

---

internal/gps/deduce.go

More liberal use of `errors.Wrap` gives more complete output, like this:
>
> % dep init
Unable to cache code.justin.tv/release/trace
sm.DeduceProjectRoot: unable to deduce repository and source type for "code.justin.tv/release/trace": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://code.justin.tv/release/trace?go-get=1": Get http://code.justin.tv/release/trace?go-get=1: dial tcp: lookup code.justin.tv: no such host
This could be improved, readability-wise, but the first step is to preserve the error information up to the caller.
Fixes #556.

Include more error context in deduction failures

---

internal/gps/deduce_test.go
internal/gps/manager_test.go
internal/gps/result_test.go

This is a small change to gps tests which removes some unused code, and cleans-up some repeated sub-test code which was unintentionally serial.

gps tests: dry and cleanup; remove unused code

---

internal/gps/pkgtree/pkgtree.go

This is a temporary fix to avoid the panic caused in #367 and #357

Add temporary solution to avoid a panic

---

cmd/dep/ensure_test.go
cmd/dep/graphviz_test.go
cmd/dep/init_test.go
cmd/dep/integration_test.go
cmd/dep/remove_test.go
cmd/dep/status_test.go
internal/test/test.go

This change parallelizes many of the `cmd/dep` tests, and reduces the running time for `go test ./cmd/dep/...` on my machine from ~21s to ~18s, with room for more improvement with more parallelism (beyond GOMAXPROCS). With `go test -parallel 16 ./cmd/dep/...`, I can get it down to ~8s. In fact, most of the `-parallel 16` speedup comes from pre-existing parallelism, and runs about ~10s on master.
So this PR offers around ~10% speedup, and it may be worth considering a CI test script change to run with more parallelism for an even better payoff.

parallelize many cmd/dep tests

---

txn_writer.go

writeFile function is duplicate of writeFile in fs.go (removed in ee9843c)
rawLockDiff struct introduced in 34bbce0 and never used
@carolynvs can you please confirm rawLockDiff removal.

Removed dead code

---

cmd/dep/main.go
cmd/dep/testdata/harness_tests/init/usage/with_h_flag/testcase.json
cmd/dep/testdata/harness_tests/init/usage/with_not_defined_flag/testcase.json
internal/test/integration_testcase.go

This fix #626 
Please notice [changes to integration_testcase.go](https://github.com/golang/dep/commit/64d1376f4a4903408952e11022fb17a565d68669)
Without this change it was impossible to write integration test to catch the bug.
Changes to `cmd/dep/main.go` are trivial.

Fix double usage message

---

internal/fs/fs.go

Would clarify errors like (from #651):
> safe write of manifest and lock: second attempt failed: cannot rename /tmp/dep666066408/vendor to /home/ser/workspace/src/foo/vendor: read /tmp/dep666066408/vendor/github.com/prometheus/procfs/fixtures/self: is a directory
to become:
> safe write of manifest and lock: **rename fallback failed**: cannot rename /tmp/dep666066408/vendor to /home/ser/workspace/src/foo/vendor: **copying file failed:** read /tmp/dep666066408/vendor/github.com/prometheus/procfs/fixtures/self: is a directory

internal/fs: update error message when rename fallback fails

---

FAQ.md

Update FAQ about nuked vendor files now that we backup on init.

FAQ: dep backs up vendor during init

---

cmd/dep/ensure.go
cmd/dep/ensure_test.go
cmd/dep/init.go
cmd/dep/init_test.go
cmd/dep/testdata/harness_tests/ensure/empty/case1/final/Gopkg.toml
cmd/dep/testdata/harness_tests/ensure/override/case1/final/Gopkg.toml
cmd/dep/testdata/harness_tests/ensure/override/case1/testcase.json
cmd/dep/testdata/harness_tests/init/case1/final/Gopkg.toml
cmd/dep/testdata/harness_tests/init/case2/final/Gopkg.toml
cmd/dep/testdata/harness_tests/init/skip-hidden/final/Gopkg.toml
internal/gps/constraint_test.go
internal/gps/constraints.go
internal/gps/version.go
internal/gps/version_unifier.go
manifest.go
manifest_test.go
testdata/manifest/golden.toml

Fixes #225 
When reading in a manifest, and no constraint has been applied to a version, assume the caret `^` constraint by default. Now a user must add the `=` prefix to restrict a version to exactly the version specified and maintain the previous behavior.
~I decided to accept implied carets but never write out implied carets, i.e. be liberal in what we accept and strict in what we output. So when `init` generates a manifest, it continues to output carets as `dep` does today. I prefer this over outputting bare versions because it is more clear to users; it should cut down on issues where someone is surprised that the version wasn't "pinned". I left comments in as to why we aren't using ImpliedCaretString.~
Existing tests which relied upon a bare version being interpreted with an `=` …

Assume an implied caret when a semver doesn't have an explicit constraint

---

cmd/dep/init.go

Check length of `notondisk` before printing deps not found in GOPATH message.
This fix was added in #497 previously, but since that PR is on hold for now, proposing the fix separately.

init print not in GOPATH only when notondisk > 0

---

.travis.yml

Fixes #662:
- added flag `HOMEBREW_NO_AUTO_UPDATE` following https://github.com/Homebrew/brew/blob/7d31a70373edae4d8e78d91a4cbc05324bebc3ba/Library/Homebrew/manpages/brew.1.md.erb#L202
- removed cache directories which took around 30s of build time according to https://travis-ci.org/golang/dep/jobs/236664226#L59
Question is if we want `HOMEBREW_NO_AUTO_UPDATE` with command or just put in `env` section, personally I think this is specific for OSx builds and shouldn't affect different platform environments.

 slow bzr installation with OSx build

---

cmd/dep/init.go

As [reported in Slack](https://gophers.slack.com/archives/C0M5YP9LN/p1496097063859182), when dep is unable to cache a project, it is not printing why. This wraps the error and prints it with a stack trace. I can remove the stack trace if we don't want that(?) but since I couldn't reproduce, I'm not sure how helpful the error message will be in pinpointing the problem.
```
Unable to cache github.com/go-sql-driver/mysql
Unable to cache github.com/newrelic/go-agent
Unable to cache github.com/jmoiron/sqlx
```

Print the error when unable to cache

---

internal/gps/bridge.go
internal/gps/hash_test.go
internal/gps/rootdata_test.go
internal/gps/solve_test.go
internal/gps/solver.go

This change converts the global `mkBridge` function var into a regular function, and instead provides an un-exported field (`SolveParameters.mkBridgeFn`) for test overrides, analogous to (`SolveParameters.stdLibFn`).

de-globalize mkBridge function var

---

internal/test/integration_testcase.go

CompareVendorPaths was output `got` instead `want` and vice versa

Fixed order in test output

---

internal/fs/fs.go
internal/fs/fs_test.go

`fs.copyFile()` currently fails when `src` is a symlink to a directory.
This PR adds 2 functions:
* `fs.IsSymlink()` to check if a path is a symbolic link.
* `fs.copySymlink()` to copy a symlink (preserves relative symlinks)
And update `fs.copyFile()` to handle symlinks correctly.
Should solve #651 .

internal/fs: handle symlinks in copyFile()

---

manifest.go
manifest_test.go

Match abbreviated git and hg commit hash, 7 and 12 characters
respectively. Warn in validateManifest if abbreviated hashes are used.
Fixes #567

Match and warn on abbreviated git and hg revisions

---

cmd/dep/status.go

- Adds feedback to status when there's a lock memo mismatch. For
mismatch with missing packages, it lists the packages and provides
instructions to fix the issue. For memo mismatch with no missing
packages, it instructs the user about how to generate a new lock.
Fixes #161 fixes #664

Add status feedback on memo mismatch

---

internal/gps/source.go

Fixes #639, fixes #699, fixes #649 (probably, so we'll gonna close it optimistically on merge).
In all these methods, I'd been relying on `sourceGateway.convertToRevision()` to update the local repo if the revision wasn't present in it. Problem is, it was checking whether the revision exists _in the cache_ - which, for git, is populated from upstream directly, without necessarily updating the local. So, this adds retry logic that retries each of the version-accepting `sourceGateway` methods  the assumption that what's in `sourceGateway.cache` is an accurate representation of what's on disk. 
However, this does highlight another problem with the generalized FSM `sourceGateway` uses for underlying `source` state management. In this case, `sourceGateway.cache` being out of sync with what's …

Guard against possibly stale local git repos

---

cmd/dep/ensure.go
cmd/dep/hash_in.go
cmd/dep/prune.go
cmd/dep/status.go
context.go
context_test.go

This change simplifies the `LoadProject` method by removing the sole `path` argument, since every usage (besides tests) passes an empty string.
Have I overlooked some future usage for this functionality (internal or external)?
#672

simplify Ctx.LoadProject

---

lock.go
manifest.go

Documenting some exported members. #672

Document lock.go and manifest.go

---

project.go
project_test.go

Replaces renaming with copying vendor/ while backing up. This keeps the
original vendor/ and lets SafeWriter.Write() preserve vendor/.git if
any.
Fixes #698

Copy vendor/ when backing up and preserve .git

---

cmd/dep/ensure.go
cmd/dep/init.go
txn_writer.go
txn_writer_test.go

#672
This PR proposes inverting a bool method parameter:
```
func (sw *SafeWriter) Write(root string, sm gps.SourceManager, noExamples bool) error 
func (sw *SafeWriter) Write(root string, sm gps.SourceManager, examples bool) error 
```
I see that using a negative makes sense for the command line flag (`no-examples`), but I don't see a compelling reason to propagate that into the library code where it seems unidiomatic and a default/zero value is not relevant.

SafeWriter.Write noExamples->examples

---

txn_writer.go

Fixes [NewSafeWriter godoc](https://godoc.org/github.com/golang/dep#NewSafeWriter) formatting.
#672

fix NewSafeWriter godoc formatting

---

internal/fs/fs_test.go

No clue why this didn't cause #643 to bomb out? `go test` was failing with
https://travis-ci.org/golang/dep/jobs/238875170#L183
```
internal/fs/fs_test.go:800: assignment count mismatch: 2 = 1
internal/fs/fs_test.go:810: not enough arguments in call to setupInaccessibleDir
have (func(string) error)
want (*testing.T, func(string) error)
```

Fix failing test build

---

internal/fs/fs.go
internal/fs/fs_test.go

Fixes #675. Old logic lost the drive letter hence subsequent comparisons
were often wrong. New code adds logic to handle volume name
separately. Test changed to always have mismatching case on
windows.

Fixes #675. Changes to HasFilepathPrefix to handle Windows better.

---

cmd/dep/glide_importer_test.go

When these tests are run in parallel, the git operations inconsistently fail in confusing ways on Appveyor, such as `remote repository at https://github.com/sdboyer/deptest.git does not exist, or is inaccessible
`.

Do not run glide config tests in parallel

---

cmd/dep/status.go

Switch from `Println` to `Printf` since the message has formatting strings. To be clear this doesn't change the output, just makes `go vet` happy.
@sdboyer @darkowlzz  I am not sure why travis didn't catch this when running `go vet` locally did?
```
$ go vet ./cmd/dep
cmd/dep/status.go:225: Println call ends with newline
exit status 1
```

Fix status message formatting

---

analyzer.go
project.go

Documenting some exported members. #672

Document Analyzer and Project

---

internal/gps/selection.go
internal/gps/solver.go

Using a value caused the versionUnifier attached to the selection queue
to be without a metrics object, resulting in panics on constraint
conflicts. What's odd is that these panics *should* happen all the time,
but seem to actually happen in only a subset of cases.
@bsed, please test that this fixes your issue, as I can't reproduce.
Fixes #725

Use pointer to versionUnifier in solver

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

This adds a maintainer's guide to CONTRIBUTING.md, and templates for issues and PRs.
cc @ibrasho @darkowlzz @carolynvs 😄 
Typos, things that don't make sense, wordiness, etc. in the guide.
Helps with #629, but doesn't quite fix it.

Maintainer's guide, et. all

---

cmd/dep/ensure.go
cmd/dep/glide_importer_test.go
cmd/dep/gopath_scanner.go
cmd/dep/hash_in.go
cmd/dep/init.go
cmd/dep/main.go
cmd/dep/prune.go
cmd/dep/root_analyzer.go
cmd/dep/status.go
context.go
context_test.go
doc.go
project_test.go
test_project_context_test.go

#672
This PR improves documentation, and refactors the API around `Ctx`, primarily by dissolving the `Loggers` struct and embedding the fields directly.

improve godoc; replace Loggers with embeded fields; refactor Ctx api

---

manifest.go
manifest_test.go

Makes manifest validation stricter with **separate errors and warnings**.
Errors are raised for invalid syntax of known elements (required, ignored,
constraint, override), which are processed later.
Warnings are raised for unknown elements and less important (metadata)
elements that are not processed later.
Fixes #702

Stricter manifest validation - errors & warnings

---

.gitignore

I like to run the same code checks from travis locally before submitting a PR, which generates a couple extra files that aren't in our `.gitignore`.

Ignore test run output files in git

---

FAQ.md

- Add pinning a version of direct dependency.
- Replace old `dependencies` with `constraint`.
fixes #734

FAQ - pinning version of a direct dependency

---

FAQ.md

[[dependencies]] was changed to [[constraint]] but the FAQ still has answers that reference the old field.
Update the FAQ to use `constraints` instead of `dependencies` where the reference is to the manifest field.

Update the FAQ to use constraint instead of dependencies (reflect #538)

---

cmd/dep/root_analyzer.go

This handles the returned error from the importer tools. Leaving this unhandled causes panic when importer fails.

Immediately handle error returned from importers

---

cmd/dep/glide_importer.go
cmd/dep/godep_importer.go
cmd/dep/gopath_scanner.go
cmd/dep/root_analyzer.go
cmd/dep/testdata/glide/expected_import_output.txt
internal/feedback/feedback.go
internal/feedback/feedback_test.go

The feedback system was originally designed for reporting feedback as GOPATH was scanned, which didn’t work well for logging from the importers. This moves more of the logic around what should be logged back onto the caller and simplifies the `ConstraintFeedback.LogFeedback` function to print what it is given.
This is broken off from #715.

Add constructors for feedback logs

---

cmd/dep/glide_importer_test.go
cmd/dep/godep_importer.go
cmd/dep/godep_importer_test.go
cmd/dep/gopath_scanner_test.go
cmd/dep/root_analyzer.go
cmd/dep/status.go
context.go
context_test.go
internal/gps/constraint_test.go
internal/gps/lock.go
internal/gps/lock_test.go
internal/gps/manager_test.go
internal/gps/result_test.go
internal/gps/solve_basic_test.go
internal/gps/solve_test.go
internal/gps/source_cache.go
internal/gps/source_test.go
internal/gps/vcs_source.go
internal/gps/vcs_source_test.go
internal/gps/version.go
internal/gps/version_queue_test.go
internal/gps/version_test.go
internal/gps/version_unifier.go
internal/gps/version_unifier_test.go
lock.go
lock_test.go

This PR proposes name changes for two gps version interface methods, primarily for the sake of readability (based on my experience working towards #431).
1) The `UnpairedVersion` interface method `Is`:
Old: `Is(Revision) PairedVersion`
New: `Pair(Revision) PairedVersion`
2) The `PairedVersion` interface method `Underlying`:
Old: `Underlying() Revision`
New: `Revision() Revision`
[Jump to interface declarations](https://github.com/golang/dep/pull/750/files#diff-4d0ad66ea351a55090725da9672b6c4e)
Reasons not to do this, or more idiomatic name alternatives.
Related to #672 and #431

Version API Method Names

---

internal/feedback/feedback.go
internal/feedback/feedback_test.go

A few PRs collided in the last merge, this fixes the rename from `Underlying()` to `Revision()`, and `Is()` to `Pair()`.

Fix build on master

---

internal/gps/maybe_source.go

This PR adds a helper function `sourceCachePath` to DRY up some existing code, with future usages coming in #431.

add sourceCachePath helper func

---

analyzer.go
analyzer_test.go
cmd/dep/root_analyzer.go
cmd/dep/root_analyzer_test.go
internal/gps/example.go
internal/gps/hash.go
internal/gps/manager_test.go
internal/gps/result.go
internal/gps/result_test.go
internal/gps/solver.go
internal/gps/source.go
internal/gps/source_cache.go
internal/gps/source_manager.go

This PR proposes a new simple struct type `ProjectAnalyzerInfo` to return from `ProjectAnalyzer.Info()`, and to use in place of `ProjectAnalyzer` in a few places which only called `Info()`. My working branch for #431 contains additional usages.
Better name or documentation opportunities. More usages of `ProjectAnalyzer` which only need `ProjectAnalyzerInfo`.
Related #672 and #431.

gps: add new ProjectAnalyzerInfo type to return from ProjectAnalyzer.Info

---

internal/fs/fs.go

Updates #632
IsRegular would previously return true if any file that was _not_ a
directory were presented. With this change IsRegular rejects any file
with a mode bit in the os.ModeType bitset--only regular files will pass
this test.

internal/fs: IsRegular returns an error on any non regular file

---

cmd/dep/glide_importer.go
cmd/dep/godep_importer.go

Add checks for error returned from deduceConstraint to avoid panic due to
passing nil constraint to feedback.
Avoids panicking when `deduceConstraint()` fails to deduce a valid constraint.

Check error returned from deduceConstraint

---

cmd/dep/testdata/harness_tests/ensure/empty/case1/final/Gopkg.toml
cmd/dep/testdata/harness_tests/ensure/override/case1/final/Gopkg.toml
testdata/txn_writer/expected_manifest.toml
txn_writer.go

Sometimes IDE/editor removes trailing spaces automatically. It causes ridiculous git diff...

Remove trailing spaces from generated Gopkg.toml

---

context.go

Remove the usage of `filepath.FromSlash` and `filepath.ToSlash` in `GOPATH`
detection functions `*Ctx.SetPaths` and `*Ctx.detectGOPATH`.
This should ensure the `GOPATH` returned from `*Ctx.DetectProjectGOPATH`
uses the filesystem separator instead of slashes.
`*Ctx.SetPaths` converts GOPATHs to use slashes. This is unnecessary and *could cause* issues on filesystems that don't use slashes as a separator.

dep: remove usage of filepath.FromSlash & filepath.ToSlash in context.go

---

internal/gps/manifest.go
internal/gps/manifest_test.go
internal/gps/rootdata.go
internal/gps/solve_basic_test.go
internal/gps/solve_bimodal_test.go
manifest.go

Fixes #429. Removed Manifest.TestDependencyConstraints() and all usage.
As per the issue description, speficying dependency now does not imply
requirement. Therefore, there is no point in differentiating normal
and test dependencies.
Issue also talks about removing pcSliceToMap. This function converts few slices to a map and works for non-test dependencies. So unless I am missing something, I don't think it can be removed.

Fixes #429. Removed Manifest.TestDependencyConstraints() and all usage.

---

context.go

This change:
1) Removes the `getGOPATHs` function
2) Embeds a slimmer version (w/o unused parameter) in place of it's only usage in `SetPaths`
3) Updates out of date docs for `SetPaths`
Related #672

remove getGOPATHS; cleanup

---

txn_writer.go
txn_writer_test.go

As reported in #775 , `dep prune` deletes all directories in `vendor`. After digging in, the culpirt seems to be `calculatePrune` in `txn_writer.go`.
[This line](https://github.com/golang/dep/blob/master/txn_writer.go#L550) assume all paths use `/` as a separator. And therefore, causes [this check](https://github.com/golang/dep/blob/master/txn_writer.go#L557) to be always `true` (on filesystems that don't use `/`) thus adding all directories to the `toDelete` slice.
Generic review.
fixes #775

dep: update calculatePrune to not assume "/" as file separator

---

cmd/dep/init.go
context.go
context_test.go

The doc for (and name of) `SplitAbsoluteProjectRoot` is stale (seems it used to check multiple GOPATHs and return the matched one).  This change proposes updates, but it's exported api so let's get the name right. Anyone have other suggestions?
#672

SplitAbsoluteProjectRoot re-name/doc

---

cmd/dep/ensure.go
cmd/dep/ensure_test.go
cmd/dep/glide_importer.go
cmd/dep/godep_importer.go
internal/gps/solve_basic_test.go
internal/gps/source_manager.go

Moves the function `deduceConstraint` to the SourceManager interface. 
I think the `DeduceConstraint` implementation for `depspecSourceManager` could be simpler, since it's a mock implementation? not sure
natm
https://github.com/golang/dep/issues/654

move deduceConstraint to SourceManager

---

cmd/dep/glide_importer.go
cmd/dep/glide_importer_test.go
cmd/dep/godep_importer.go
cmd/dep/godep_importer_test.go
cmd/dep/root_analyzer.go
cmd/dep/root_analyzer_test.go
cmd/dep/testdata/glide/golden.txt
cmd/dep/testdata/godep/expected_import_output.txt
cmd/dep/testdata/harness_tests/init/godep/case1/final/Gopkg.lock
internal/gps/source_manager.go
internal/gps/source_manager_test.go

Fixes #710. When a user supplied string in an imported config file, or specified to `dep ensure`, can be interpreted multiple ways, prefer the branch over a semver constraint.
In #710, `glide.yaml` specified `v2` for `https://github.com/go-mgo/mgo`. When we assume that is a semver constraint, solve fails because the hinted revision in the lock (a commit on the v2 branch) doesn't satisfy the assumed constraint of `^2.0.0`.
The new preferred match order for the user string is:
* revision
* branch
* semver constraint
* tag
I am giving preference of a semver constraint over a tag so that a bare version, `1.0.0`, is interpreted more loosely with an implied caret, `^1.0.0`, instead of the stricter exact match.

Interpret strings as branches > semver constraints

---

context_test.go
internal/fs/fs.go
internal/fs/fs_test.go
project.go
txn_writer.go

As the issue states `fs.isDir` should always return an error and not just false if the directory is not found.
Altering of `fs.isDir` returned error. The unit tests have been adjusted accordingly but the integration tests are still having issues.
Yes. It seems the integration tests have a `testcase.json` where expected errors are listed. However since `fs.isDir` now potentially returns large, complex errors from `os.Stat` simple error matching on the strings will not be possible. If the change to the code is what the issue is calling for then I would need some help/clarification on how to handle the new integration test expectancies. 
The test case ion question:
`go/src/github.com/golang/dep/cmd/dep/testdata/init_path_tests/relative_path/testcase.json`
fixes #642

fs.isDir return error when directory is not found

---

cmd/dep/prune.go
cmd/dep/prune_test.go
txn_writer.go
txn_writer_test.go

This change unexports the `PruneProject` function and moves it and associated helpers into `prune.go`, alongside the only usage.
#672

unexport and re-locate PruneProject and helpers

---

FAQ.md
docs/Gopkg.toml.md

Add document for `version` property of `constraint` and `override`.
Help in improving the proposed document addition.
fixes #808

docs: Gopkg.toml.md version

---

cmd/dep/ensure.go
cmd/dep/ensure_test.go
cmd/dep/testdata/harness_tests/ensure/pkg-errors/case1/testcase.json

Running dep ensure would generate unhelpful output when directories had code with errors or no go code. This prints the import path of the package with either "no go code" or the build error message. This gives us output like:
```
Found 3 errors:
λ dep ensure
Found 97 errors:
/Users/grepory/go/src/github.com/golang/dep/internal/gps/_testdata/src/bad/bad.go:6:43: expected 'package', found 'EOF'
import path github.com/golang/dep/internal/gps/_testdata/src/relimport/dotdotslash had a local import: "../github.com/golang/dep/internal/gps"
import path github.com/golang/dep/internal/gps/_testdata/src/relimport/dotslash had a local import: "./simple"
import path github.com/golang/dep/internal/gps/_testdata/src/relimport/dotdot had a local import: ".." …
```

Better error reporting from dep ensure when packages have errors

---

internal/feedback/feedback.go
internal/feedback/feedback_test.go

Update feedback to support revision without version. 
Doing this so we can get feedback for the detached head
use case that govendor frequently has.
Without this change we won't get any feedback for locks that have a revision, but no version.  This can happen if we are using `gps.Any()` for the constraint.
Without this fix you might see something like the following: 
```
Using * as initial constraint for imported dep github.com/sdboyer/deptest
```
After this fix you should see something like : 
```
Using * as initial constraint for imported dep github.com/sdboyer/deptest
Trying * (c575196) as initial lock for imported dep github.com/sdboyer/deptest
```
No.
None

Update feedback to support revision without version

---

cmd/dep/gopath_scanner.go
context.go
context_test.go
internal/gps/vcs_version.go
internal/gps/vcs_version_test.go

#672 
The `VersionInWorkspace` logic is coupled to `Ctx` as a method, although it only accesses `Ctx.absoluteProjectRoot()`.
This change proposes dissolving `VersionInWorkspace` in favor of a new func with the interesting logic (`gps.ProjectVersion`) and exporting `absoluteProjectRoot` (currently named `AbsForImport`, but should coordinate with #682 ).

Break up Ctx.VersionInWorkspace

---

Gopkg.lock
internal/gps/manager_test.go
internal/gps/source_manager.go
vendor/github.com/nightlyone/lockfile/.gitignore
vendor/github.com/nightlyone/lockfile/.gitmodules
vendor/github.com/nightlyone/lockfile/.travis.yml
vendor/github.com/nightlyone/lockfile/LICENSE
vendor/github.com/nightlyone/lockfile/README.md
vendor/github.com/nightlyone/lockfile/appveyor.yml
vendor/github.com/nightlyone/lockfile/lockfile.go
vendor/github.com/nightlyone/lockfile/lockfile_test.go
vendor/github.com/nightlyone/lockfile/lockfile_unix.go
vendor/github.com/nightlyone/lockfile/lockfile_windows.go

Adds https://github.com/nightlyone/lockfile to manage the lockfile that dep uses. Concurrent use of dep no longer fails, subsequence invocations of dep will cause the subsequence instances to wait while the first runs, and then they will continue.
Also, stale lockfiles are handled correctly.
Correctness.
How to use git ... ;-)
fixes #820 
fixes #852

source_manager.go handle locking better

---

internal/gps/constraint_test.go
internal/gps/constraints.go
internal/gps/lock.go
internal/gps/source_cache.go
internal/gps/source_cache_test.go
internal/gps/version.go
internal/gps/version_unifier.go

This change adds tests for `singleSourceCache` against the only current implementation, `singleSourceCacheMemory`. They are more general than they need to be (e.g. equality funcs, `cachedLock/Manifest` types), but this is in anticipation of being run against a persistent `singleSourceCache` as well for #431 (which can't rely on `==` or `reflect.DeepEquals` as liberally).

adding TestSingleSourceCache

---

.github/CODEOWNERS
MAINTAINERS.md

Adds myself to MAINTAINERS and CODEOWNERS for gps caching.
Related #629

add jmank88 to MAINTAINERS and CODEOWNERS for gps caching

---

cmd/dep/init.go
cmd/dep/init_test.go
cmd/dep/testdata/init/directdeps/main.go

At the end of `dep init`, the `rootAnalyzer` [removes any constraints that are not direct dependencies](https://github.com/golang/dep/blob/6c5ebb93c4e32614ba61fed6acb962a272ad4b8a/cmd/dep/root_analyzer.go#L94). If only a subpackage was imported, never the root package from the dependency, then it (incorrectly) removes the constraint for the dependency.  The direct dep was added to the map as a full subpackage, when the constraint is only the root package.
This fixes `getDirectDependencies` to return only root packages. Now when we lookup constrains in the directdeps map, we are comparing root projects to root projects.

Consolidate direct deps by root project

---

CONTRIBUTING.md
README.md
docs/FAQ.md
docs/Gopkg.toml.md

Hello from Gophercon! I'm a new Dep user/contributor, so decided to work on the first-run experience in terms of documentation.
See the commit messages for details (I tried to keep each one small/discrete), but the high-level overview is:
* Moved the FAQ under the `docs/` folder, to have one less file at the top level
* This could probably be done with other files, but I didn't want to get too carried away.
* Split and expand the Usage information into initial setup and day-to-day interactions with Dep
* Don't encourage adding/changing of dependencies through the CLI directly
* Minor formatting fixes
Whether the updated instructions are still recommended/accurate.
I don't _think_ so, but I don't know what I don't know.
None.

documentation improvements for new users

---

internal/gps/cmd.go
internal/gps/cmd_test.go
internal/gps/cmd_unix.go
internal/gps/cmd_windows.go

This should help address the overwhelming majority of reports of cache corruption, which occur as a result of Ctrl-c causing git to exit abruptly and leaving a corrupted repository state on disk. Given how common it is for people to Ctrl-c during their first dep init while dep is cloning down bunches of repos, this could help a lot. As @natefinch put it in #823:
> Even though dep is actually doing something, it's a long process, and thus it looks like it is hanging. Because it looks hung, people hit ctrl-C, which then corrupts the dep cache, and screws up further dep init attempts.
Note that this PR sidesteps the problem for Windows. I'm hoping one of our Windows folks might be able to do a follow-up on that side - @ChrisHines? @mattn? (I did see …

Use gentler subprocess termination semantics

---

internal/gps/cmd.go
internal/gps/cmd_test.go

`*monitoredCmd.combinedOutput` and `gps.TestMonitoredCmd` used to access `monitoredCmd.stdout` and `monitoredCmd.stdout` (both of type `gps.*activityBuffer`) without obtaining a lock on `activityBuffer.Mutex`.
This caused the tests to fail on rare occasions. This change adds 2 methods to ensure reads from to the underlying `bytes.Buffer` happens only when a lock is obtained.
General review.
Might fix one of the causes of #763

internal/gps: Resolve possible race in gps.activityBuffer

---

cmd/dep/godep_importer_test.go
internal/gps/source_manager.go
internal/gps/source_manager_test.go

This PR handles the case in the `godep_importer` where the imported dependency is referencing a semantic version with a suffix. E.g. 
```
{
"ImportPath": "github.com/Shopify/sarama",
"Comment": "v1.12.0-12-g2fd980e",
"Rev": "2fd980e23bdcbb8edeb78fc704de0c39a6567ffc"
},
```
Will now become:
```
[[constraint]]
name = "github.com/Shopify/sarama"
version = ">=1.12.0, <=12.0.0-g2fd980e"
```
As per my understanding it is fine to assume that `bzr` revisions contain `@` symbols. But I'm not a `bzr` user so I'm half guessing (with some reading on the Internet) that it's valid.
I think I've gotten what I needed in #827.
There was a comment in the code that I modified that was a bit too long. I have wrapped it. Don't know if you'd like to keep such things out of the PR. Let me know and I can drop …

Address mixup between bzr revisions and semver suffixes

---

internal/gps/cmd.go
internal/gps/vcs_repo.go
internal/gps/vcs_source.go

both `runFromRepoDir` and `runFromCwd` accept now a timeout to control the timeouts of the underlying `monitoredCmd`, instead of having a hardcoded timeout of 2 minutes for all commands.
This will allow better tuning of the timeouts on a per-command basis.
Right now, as the timeouts are really naive I've just added two kinds of timeouts:
* `expensiveCmdTimeout`: a cmd that is expensive such as clones, fetches, updates, ...
* `defaultCmdTimeout`: any other non-remote or non-expensive cmd
I expect these to change during the review when the timeouts are better adjusted, anyway 😛 
The timeouts are a bit naive right now. I am familiar with git commands but not with all other vcs commands, so the rule I followed was: remote -> expensive, non-remote -> default timeout. So if you see a timeout …

use different timeouts for all vcs commands

---

README.md

It adds documentation to the readme regarding the mismatch lock state in `dep status`
@carolynvs mentioned in the issue that modifying the `Gopkg.toml` should also generate the same message when you run `dep ensure`, but I tried and I did not get such message. Only when I added the import. Should I report it as a bug?
Fixes #876

document lock mismatch state for ensure

---

internal/test/integration_testproj.go

If the tempdir is evaluated on creation, there is no need for special
handling of "darwin" (OSX) in NewTestProject()
It simplifies the code in `NewTestProject()` (`internal/test/integration_testproj.go`) by removing special handling when `runtime.GOOS == "darwin"`. 
The problem is that tempfiles[1] on OSX are symlinks and it's just simpler to EvalSymlinks when the test directory is created than having special handling for `"darwin"` later.
[1] An example temp directory on OSX:
tmpDir: /var/folders/np/f6xzpfd94217nvgdpmwt_qbr0000gn/T/gotest259673386
...it symlinks to: /private/var/folders/np/f6xzpfd94217nvgdpmwt_qbr0000gn/T/gotest259673386

Simplify temp dir creation in tests

---

cmd/dep/testdata/glide/golden.txt
internal/gps/source_manager.go
internal/gps/source_manager_test.go

When a package is specified without any restrictions, default the constraint to `gps.Any()`, not latest from the default branch.
Work in pending pull requests for the importers has made it clear that this change is universally needed and shouldn't be done one-off in each importer.

Default an empty constraint as any, not latest

---

internal/gps/vcs_source.go
internal/gps/vcs_source_test.go

Remove VCS related directory (`.hg` and `.bzr`) when copying dependencies to `vendor/`
Correctness.
Fixes #887

internal/gps: remove vcs (bzr & hg) directories when coping to vendor/

---

docs/Gopkg.toml.md

The current wording is not clear on the fact that it won't install the packages in the required list. This can be confusing, because usually this is what you expect for linters and generators.
I put in a link to [virtualgo](https://github.com/GetStream/vg) as well, because it solves the issue as well. If desired I can remove it, but I thought it would be alright because there's also one in the README.

Expand on what the required list does and doesn't do

---

cmd/dep/status.go
cmd/dep/testdata/harness_tests/status/without_lock/testcase.json

`dep status` error out when no lock is found and suggest steps to
generate lock file.
Error message and test case.
No.
fixes #891

fix(status): error out when lock not found

---

cmd/dep/ensure.go

If the vendor directory already exists, and the lock file hasn't
changed, even though a project may be missing from the vendor
directory, dep ensure would not add the dependency to the vendor
folder.
If the project is in the vendor folder, but it has been modified
(no longer in sync with lock file), ensure would not replace the
dependency in the vendor folder.
This change causes dep ensure to run anytime there's a solution,
regardless of the state vendor folder is in, erring on the side
of replacing vendor without checking existing state which is the
most correct behaviour given the ensure intention.
Future optimisations may want to check and verify the contents of
the vendor folder before blinding replacing it.
Check the original issue #883, and then my initial proposal PR in #884, …

ensure: always write vendor even if not empty

---

docs/FAQ.md

Adds a FAQ item "Does dep support relative imports?" to docs/FAQ.md. Created in response to https://github.com/golang/dep/issues/910. 
Clarity of explanation and correct style - I tried to follow the FAQ's standard structure by pulling an explanation from existing issue discussion and quoting the author / linking to the page. 
Happy to make changes to this if the content needs work!

Add item on relative imports to FAQ

---

cmd/dep/main.go

Fixed the add dependency example in ```dep's``` help message.
Closes #951

fixes #951

---

internal/gps/source_manager.go

waiting for something, we at least print a message to stderr about it.
Hopefully will make situations like what is described in #947 obvious.
If dep has to wait for the sm.lock file, currently there's no feedback that its waiting. This provides feedback.
may address #947

Added warning message to the lockfile waiting routine.

---

Gopkg.lock
Gopkg.toml
cmd/dep/godep_importer_test.go
vendor/github.com/Masterminds/semver/constraints.go
vendor/github.com/Masterminds/semver/constraints_test.go
vendor/github.com/Masterminds/semver/parse.go

Use fix from PR https://github.com/Masterminds/semver/issues/60 until it is merged (or https://github.com/Masterminds/semver/issues/59 is otherwise fixed upstream).
Do we want to use a PR that we aren't sure will be merged?
Nope!
I am not sure if we have an existing issue but it was found when was working through what we need to fix in order for a project like kuberentes to use dep. See https://github.com/fabulous-gopher/k8s-dep-e2e/issues/3.
Fixes #924

Use fork of Masterminds/semver until PR is merged

---

internal/gps/solve_bimodal_test.go
internal/gps/solver.go

Fixes #969. This is insanely deep in the solver, so I'm not actually expecting anyone to review it.
In short, when we encountered a dependency for the second time, and the first time established an alternate `source`, but the second time did not (a case we allow for now even though it's maybe kind of a bad idea - #428), we weren't keeping track of that alternate source on the new bimodal identifier that was pushed into the unselected queue.
We have a new test case that now and only passes with the new change.

Unify alternate source IDs in solver to avoid duplicate projects

---

internal/gps/solver.go

When the version from the lock is immediately discarded due to not matching the constraint, nothing is logged and it's not clear that the lock was broken, or why. Allowing it be be added to the version queue lets it be evaluated first, traced and clearly show why it wasn't used.
I originally tried to log directly in `getLockVersionIfValid` but it caused the trace to look out of order, since that is called before the top level line is printed for the package being evaluated.
I don't think so.
I wasn't sure if there was an existing gps unit test/fixture I could piggy back on to validate this new behavior, short of testing the output in a harness test. If not, I'll add a harness test and just check the output.
This is related to #939, so that at least something is logged when the lock is …

Allow invalid lock version to be added to the Q

---

cmd/dep/glide_importer.go
cmd/dep/glide_importer_test.go
cmd/dep/godep_importer.go
cmd/dep/godep_importer_test.go
cmd/dep/root_analyzer.go
cmd/dep/root_analyzer_test.go
cmd/dep/testdata/harness_tests/init/glide/case1/final/Gopkg.lock
cmd/dep/testdata/harness_tests/init/glide/case1/final/Gopkg.toml
cmd/dep/testdata/harness_tests/init/glide/case1/initial/glide.lock
cmd/dep/testdata/harness_tests/init/glide/case1/initial/glide.yaml
cmd/dep/testdata/harness_tests/init/glide/case1/initial/main.go
cmd/dep/testdata/harness_tests/init/glide/case1/testcase.json

I (naively) assumed that since glide supports listing the subpackages used, that it people's glide.yaml/lock wouldn't have multiple entries for the same root package...
The glide importer now checks for duplicate root projects. I've introduced a cache of the resolution from import path to root project, because it's guaranteed that paths will be double resolved (for glide and any other future importer that uses a config + lock).

Remove duplicate root projects when importing from glide

---

FAQ.md

Just some words for the faq / Because you asked for them in #856 
no sharp edges here.
Nope 👍 
#865

FAQ entry for issue #856, (anyway I *think* this is how it works)

---

cmd/dep/ensure.go
cmd/dep/testdata/harness_tests/ensure/add/all-new-double/final/Gopkg.toml
cmd/dep/testdata/harness_tests/ensure/add/all-new/final/Gopkg.toml

This completes a major bit of #489 that was missing - converting whatever's in the lock to a constraint that we can append into `Gopkg.toml` when no version constraint was given on the CLI.
This was easier than i thought it would be. Have i missed something?

Fix missing branch in dep ensure -add: introduce hoist from lock

---

cmd/dep/ensure.go
cmd/dep/init.go
cmd/dep/prune.go
internal/gps/lock.go
internal/gps/lock_test.go
internal/gps/result.go
internal/gps/result_test.go
txn_writer.go
txn_writer_test.go

Add logging parameter to `gps.WriteDepTree` and `sw.Write` to print each step if verbose option is selected. 
- Updated `sw.Write` and `gps.WriteDepTree`
- Appended nil as logger for tests using these functions
- LockedProject implements Stringer interface since both `sw.PrintPreparedActions` and `gps.WriteDepTree` logs LockedProject to user. 
I implemented as we speak in #963. It might be better to implement this functionality inside SourceManager.
fixes #963

Add verbose logging option to WriteDepTree

---

cmd/dep/ensure.go
cmd/dep/init.go
cmd/dep/status.go
context.go

Same as #697 
Ensure that we validate `gps.SolveParameters` in `dep init`, `dep status` and the new modes in `dep ensure`.

cmd/dep: always ensure that gps.SolveParameters are validated

---

cmd/dep/prune.go
cmd/dep/prune_test.go

Modify `prune` to use discardlogger.
With #952 merged this pr will be unnecessary.
Fixes #1003

Fixes #1003

---

cmd/dep/glide_importer_test.go
cmd/dep/godep_importer_test.go
cmd/dep/root_analyzer_test.go

#897 took the first steps to standardize what all the importers test. This takes it a bit further so that each importer isn't re-implementing the validations. I also noticed a few properties weren't being validated consistently:
* Remove `matchVersionPair` flag and validate the cast anytime a `wantRevision` was specified.
* Always validate lock properties when a lock is generated.
Heads up: This will impact #978.

Apply common validations to all import conversion unit tests

---

docs/FAQ.md

Fixes the broken link in FAQ.md
Just the doc URL.
I think, this is the right path. 
This is a minor fix. But, feel free to let me know if I should create an issue for this.
Thanks.

 Correct the Gopkg.toml vs Gopkg.lock URL in FAQ.md: /docs is missing in the URL

---

cmd/dep/status.go

Adds verbose messages to `status`. This is required to provide some feedback when the operation takes too long.
```
$ dep status -v
Checking upstream projects:
github.com/Masterminds/semver
github.com/Masterminds/vcs
github.com/armon/go-radix
github.com/go-yaml/yaml
github.com/nightlyone/lockfile
github.com/pelletier/go-buffruneio
github.com/pelletier/go-toml
github.com/pkg/errors
github.com/sdboyer/constext
...
```
Verbose message. Maybe better wording?
Anything else that we can log here?
Related to #1008

fix(status): print verbose messages

---

internal/gps/result.go

This commit updates WriteDepTree to parallelize write projects to the
vendor directory.
This change gives a decent speed boost when writing `vendor` directory.
Correctness.
This somehow became part of #952 even though it's not really related. 😁

internal/gps: parallelize WriteDepTree

---

internal/gps/maybe_source.go
internal/gps/source.go
internal/gps/source_cache.go
internal/gps/source_cache_test.go

Changes a `singleSourceCache` method's signature from `storeVersionMap(versionList []PairedVersion, flush bool)` to `setVersionMap(versionList []PairedVersion)`, because all current usages flush and it simplifies the implementations (particularly for the persistent cache, since timestamps/TTLs come into play).
There are also some small related optimizations sprinkled in.
Reasons to leave the `flush` parameter as is.
Nope.
Related to #431 - Preparation for persistent cache.

gps: source cache: interface tweaks and implementation optimizations

---

internal/gps/result.go
internal/gps/strip_vendor.go
internal/gps/strip_vendor_windows.go

defends against errors/panics in the `filepath.WalkFunc` we use to strip out vendor directories, `gps.stripVendor()`
fixes #1022

Guard against errs in stripVendor WalkFunc

---

cmd/dep/init.go

This proposes some additional verbose logging for `init`. It fills in some of the downtime before the solver starts logging.
Example output (with fancy diff highlighting I just discovered):
```diff
dep init -v
+ Getting direct dependencies...
+ Checked 4407 directories for packages.
+ Found 39 direct dependencies.
Root project is "github.com/treeder/functions"
...
```
Better log message/format ideas. Should we consider logging incrementally while scanning the directories as well?
I didn't see an issue for `init -v`, but #1008 covering `status -v` is related

init: more verbose logging

---

cmd/dep/ensure.go
txn_writer.go

This PR proposes a few tweaks to the `ensure` command, which intend only to increase consistency and orthogonality:
- log about synced lock file sooner (so included regardless of `no-vendor`)
- respect `no-vendor` even if the lock file was not already synced
- align `dry-run` logging via `PrintPreparedActions` usages
- modify `PrintPreparedActions` to handle verbosity
Oversights, better log messages.

ensure: tweaks to align no-vendor behavior and verbose/dry-run logging

---

cmd/dep/status.go

Small tweak to verbose status output adding counts so that progress can be roughly monitored.
Before:
```
Checking upstream projects:
cloud.google.com/go
github.com/Azure/azure-sdk-for-go
... (many more projects)
gopkg.in/yaml.v2
honnef.co/go/tools
PROJECT ...
... (table)
```
After:
```
Checking upstream projects:
(1/129) cloud.google.com/go
(2/129) github.com/Azure/azure-sdk-for-go
... (many more projects)
(128/129) gopkg.in/yaml.v2
(129/129) honnef.co/go/tools
PROJECT ...
... (table)
```
Follow up from #1009, related to #1008

status: adding counts to verbose output

---

cmd/dep/ensure.go
cmd/dep/glide_importer.go
cmd/dep/godep_importer.go
cmd/dep/godep_importer_test.go
cmd/dep/gopath_scanner.go
cmd/dep/gopath_scanner_test.go
cmd/dep/root_analyzer.go
cmd/dep/vndr_importer.go
cmd/dep/vndr_importer_test.go
manifest.go
manifest_test.go
project_test.go

The constructor will be used to ensure the prune variable is always set to prune nested `vendor/` dirs.
Did I replace all initializations of `dep.Manifest`?
Breaking down #952

dep: Add Manifest constructor

---

internal/fs/fs.go
internal/fs/fs_test.go

`os.Chmod` doesn't work when the passed path is longer than regular path on Windows (<= 248 characters) unless the path in extended-length form. 
Correctness.
Fixes #774

internal/fs: fix os.Chmod on Windows with long paths

---

cmd/dep/ensure.go
cmd/dep/ensure_test.go
cmd/dep/testdata/harness_tests/ensure/pkg-errors/case1/testcase.json
cmd/dep/testdata/harness_tests/ensure/pkg-errors/case2/testcase.json

`checkErrors` currently doesn't allow `dep ensure` to be used in a project that contains any Go files with build errors. This PR update `checkErrors` to return a warning instead of an error as long as the project contains some compilable Go files.
Does this make sense?
Why did we add that check in the first case?
Fixes #995

cmd/dep: make checkErrors more lenient

---

cmd/dep/vndr_importer.go

#1013 found a bug in the validation for our vndr importer.  It was relying on a later function erroring out when no import path is present in the config file, instead of explicitly checking for it.
This is small and is blocking another PR, so I'm going to merge myself once the tests pass.
Nope.
Unblocks #1013

cmd/dep: fix vndr importpath validation

---

internal/gps/source.go
internal/gps/source_manager.go
internal/gps/source_manager_test.go
internal/gps/vcs_source.go

This changes the SourceManager's `InferConstraint` method to look up any revisions which are present in the source for a project. It does this as a last-gasp effort so that it doesn't prematurely expand a tag or a branch name into a precise commit. In practice, this means it will expand any abbreviated git commit identifiers.
While dep doesn't want to encourage the use of abbreviated git commit identifiers, they come up frequently when we parse vendoring specifiers (like glide.yaml) of existing projects. We should give a shot at parsing these and then expanding them to their unabbreviated form.
It is totally possible that there are unintended consequences here. I don't know all the ways in which InferConstraint's output is used.
I also don't know anything about how caching plays in here. …

internal/gps: Parse abbreviated git revisions

---

internal/gps/source.go

Drops `convertToRevision`'s `sourceHasLatestLocally` requirement, and optimizes the `sourceHasLatestVersionList` requirement check. This should increase cache hits.
Correctness.
Related to #431

gps: source: requirements tweak

---

README.md

This fixes the URL of the `go get` command in the Setup section of the documentation.
Without this, it of course shows an error.
```
fatal: could not read Username for 'https://github.com': terminal prompts disabled
package github.com/dep/cmd/dep: exit status 128
```

Add 'golang' to go get URL of Setup instructions

---

cmd/dep/glide_importer_test.go
cmd/dep/godep_importer_test.go
cmd/dep/root_analyzer.go
cmd/dep/root_analyzer_test.go
cmd/dep/testdata/vndr/golden.txt
cmd/dep/vndr_importer.go
cmd/dep/vndr_importer_test.go

I missed this during my review of the [original vndr PR](https://github.com/golang/dep/pull/978/). When I went to update the vndr tests to use the new standardized importer validations, it found some bugs when setting a constraint from a revision:
* When a revision is specified, if it's tagged with a semver, use that to default a constraint.
* When it's a revision, and we can't guess a constraint, use `gps.Any` instead of the revision itself (never pin during import).
FYI, after this is in I'll fix govend's importer in a separate PR. It isn't using `gps.Any` when the constraint can't be inferred.
Anything else I missed... The new validations do a good job of catching mistakes as long as we are feeding in all the appropriate test cases. I did tweak the validations to always check …

cmd/dep: fix vndrImporter's rev->constraint logic

---

cmd/dep/root_analyzer_test.go

Correct message var placement in root_analyzer_test.go.

root_analyzer_test: correct message var placement

---

internal/gps/identifier.go
internal/gps/result.go
txn_writer.go

This change adds counts to some of the verbose logging lists:
1) `dry-run` vendor directories (`Would have written..`)
2) normal run vendor directories (`Wrote...`/`Failed to write...`, previously logged `Writing...` prior to work)
3) normal run vendor errors list (`Failed to write dep tree...`)
2 is concurrent and I/O limited, so this should help communicate progress to the user. 1 and 3 log immediately, but I still think the count/total is valuable for reference, grouping, and just scrolling through a really long list.
Example:
```
...
(46/84) Wrote github.com/pelletier/go-buffruneio@v0.2.0
(47/84) Wrote github.com/go-openapi/validate@master
(48/84) Wrote github.com/golang/groupcache@master
(49/84) Wrote github.com/go-openapi/analysis@master
(50/84) Wrote …
```

vendor directory writes: add counts to verbose logging, limits writers, abort on error

---

internal/gps/cmd.go

This adds the arguments from a `monitoredCmd` to any errors returned so that we get some more context.
For Example:
```diff
- *  failed to export google.golang.org/api: command killed after 30s of no activity
+ *  failed to export google.golang.org/api: command failed: [dep init -v]: command killed after 30s of no activity
```

gps: cmd: add command args to monitoredCmd errors

---

internal/gps/identifier.go
internal/gps/lock.go
internal/gps/manager_test.go
internal/gps/solve_basic_test.go
internal/gps/solve_bimodal_test.go
internal/gps/solve_failures.go
internal/gps/solver.go
internal/gps/trace.go

Follows up from #1043 ([comment](https://github.com/golang/dep/pull/1043/files#r134214321)) to remove the `ProjectIdentifier.errString()` method, and move the implementation into `String()`. Callers now implicitly call `String()` instead.

gps: ProjectIdentifier: drop errString()method in favor of implicit String() calls

---

.travis.yml

Update CI deployment stage go version to 1.9.
travis.yml different stages go versions.

Update go version of CI stages

---

cmd/dep/root_analyzer.go
cmd/dep/root_analyzer_test.go

Different names should be used _only_ for different solve algorithms. Otherwise running dep init then dep ensure will always result in a modified lock hash.
Nothing.
Nope.
fixes #917

cmd/dep: fix analyzer to always use the same name

---

cmd/dep/init.go
cmd/dep/status.go
context.go
internal/gps/source_manager.go

Just a bit of error cleanup. 
- Leverage implicit `ProjectIdentifier.String()`
- Swap in `errors.Wrap...` when tacking the error on as the last argument to `Errorf`

cleanup errors

---

cmd/dep/gopath_scanner.go
context.go
context_test.go
internal/fs/fs.go
internal/fs/fs_test.go

Add a new method to `internal/fs` to check for path equivalence.
Does this work as expected?
fixes #772
fixes #805

[WIP]: internal/fs: add EquivalentPaths function

---

cmd/dep/ensure.go
cmd/dep/testdata/harness_tests/ensure/add/errs/desync/testcase.json
cmd/dep/testdata/harness_tests/ensure/update/errs/desync/testcase.json

Update out of sync error message from:
> Gopkg.toml and Gopkg.lock are out of sync. Run a plain dep ensure to resync them before attempting to -add
to:
> Gopkg.lock is out of sync with either Gopkg.toml or the project code. Run a plain dep ensure to resync them before attempting to -add
for both add and update.
Any better suggestions?
fixes #1104

Update out-of-sync error message in ensure

---

internal/gps/manager_test.go

Use the new canonical project URL (note the lowercase 's') for logrus to prevent duplicate checkouts & imports of logrus.
See: https://github.com/sirupsen/logrus/pull/384

Replace import path 'Sirupsen/logrus' with 'sirupsen/logrus'

---

internal/gps/source_errors.go

This PR addresses a `TODO` from`unwrapVcsErr`:
```go
// TODO this is really dumb, lossy, and needs proper handling
func unwrapVcsErr(err error) error {
...
```
This function was returning errors like `<message>: <command output>`, and ignoring the available `error`.
Now it wraps up the error like we've been doing elsewhere: (`errors.Wrap(err, out)`), and then wraps *that* error with the message.  This way nothing is missing from output, and we get a more complete `errors.Wrap` trail preserving underlying types, stack traces, etc.

gps: unwrapVcsErr cleanup

---

internal/gps/source_cache_bolt_test.go

This PR aims to improve the flaky `TestBoltCacheTimeout`, which randomly fails on CI and for some people locally (I haven't actually reproduced it).  For the purpose of the failing test, we can just force a future timestamp.

gps: source cache: fix flaky bolt test

---

internal/gps/vcs_source.go
internal/gps/vcs_source_test.go

The code that determines the versions of a git repository assumes that all git repositories have a `HEAD`. It panics when this is not the case.
Not sure if the big comment block above the changes should be edited.
Is using the zero value of `Revision` like this okay?
Fixes #1051, Fixes #1112

Don't assume every git repository has a HEAD

---

internal/gps/source_errors.go
internal/gps/source_errors_test.go

In #1121 I didn't anticipate that incoming vcs errors could have nil original errors, and the result is a nil return value: https://github.com/golang/dep/issues/1128#issuecomment-328268278
This PR adjusts `unwrapVcsErr` to recognize nil original errors, and wrap them differently.
Should fix -> #1128, but let's not close until confirmed.

gps: fix unwrapVcsErr to handle nil causes

---

docs/FAQ.md

The current FAQ is misleading. When you don't commit vendor, you must run `dep` ensure after most git operations, not just a fresh clone. Otherwise you will have an out-of-date `vendor/` whenever someone updates the Gopkg.lock.
Honestly, based on this, I have now completely flipped positions on committing vendor, and tell everyone who asks "Yes, commit it!" 😀 
Let me know if I'm totally misunderstanding when you have to run dep ensure if you don't commit vendor.
Nope.

Clarify when to run ensure when vendor is not committed

---

cmd/dep/base_importer_test.go
cmd/dep/glide_importer_test.go
cmd/dep/godep_importer_test.go
cmd/dep/gopath_scanner_test.go
cmd/dep/govend_importer_test.go
cmd/dep/vndr_importer_test.go

The AppVeyor(Windows) build is failing with the following error and I can't figure out why.
```
remote repository at https://github.com/carolynvs/deptest-importers does not exist, or is inaccessible
```
I originally tried to fix this by making sure that each test had it's own separate GOPATH, and that they are all using `h.Parallel()`. I've left that in, even though it didn't fix the tests on Windows.
Nope, just need to get the build working again. Since AppVeyor isn't kicking off right now for this repo, here's a link of the build passing on my branch:
https://ci.appveyor.com/project/carolynvs/dep/build/4
Let's just get the build working again. If someone knows how to fix this, please jump in and submit a PR, making sure that the [AppVeyor …

Disable parallel importer tests

---

docs/FAQ.md

Adds documentation about a second option to interact with
private repositories, in particular for those who wants to use
a Github Token either locally or in a CI System.
Grammar or misspelled words.
It is not fixing any issues but it might help others in particular with these issues:
- https://github.com/golang/dep/issues/174
- https://github.com/golang/dep/issues/286

How to use a Github Token in .netrc file

---

internal/gps/maybe_source.go

It was previously possible for the following to occur:
```
$ dep ensure
ensure Solve(): remote repository at https://code.googlesource.com/gocloud does not exist, or is inaccessible
```
This patch exposes the underlying error:
```
chdir /Users/tamird/src/go/pkg/dep/sources/https---code.googlesource.com-gocloud: no such file or directory
```
Which is easily fixed:
```
$ rm -r /Users/tamird/src/go/pkg/dep
```

gps: avoid hiding errors

---

internal/gps/manager_test.go
internal/gps/maybe_source.go
internal/gps/source.go
internal/gps/vcs_source.go
internal/gps/vcs_source_test.go

`gopkg.in`-based sources were not isolating correctly, causing odd behaviors such as those encountered in #1119 and #1105.
nothing in particular. yes, it should be fine for us to be a little dishonest in that `upstreamURL()` method.
fixes #1119
fixes #1105

Properly separate sources for different gopkg.in versions & github

---

cmd/dep/ensure.go
cmd/dep/status.go
manifest.go
manifest_test.go

Validating ProjectRoot(s) require source manager, which is created after
loading the project. Hence, ProjectRoot validation can't be done in
existing validateManifest.
This change adds `ValidateProjectRoots()` which validates only the Constraint
and Override names to be valid ProjectRoot. Warnings are issued at stderr when
invalid ProjectRoot is found in manifest.
`ensure` and `status` call `ValidateProjectRoots()` expecitly.
Validates ProjectRoots in manifest.
The warning and error messages.
Should we warn or just error out when an invalid ProjectRoot is found?
fixes #984

fix(manifest): validate project roots in manifest

---

internal/gps/deduce.go
internal/gps/source.go
internal/gps/source_manager.go

Remove unnecessary getLifetimeContext method while I'm here.
Removes unnecessary code.
Nothing, this is simple.
No.
None.

gps: remove unused context.WithCancel

---

.travis.yml
cmd/dep/godep_importer_test.go
internal/gps/manager_test.go
internal/gps/result_test.go
internal/gps/solve_test.go
internal/gps/solver_inputs_test.go
internal/gps/source_cache_bolt_test.go
internal/gps/source_cache_test.go
internal/gps/source_manager_test.go
internal/gps/source_test.go

`go vet`, in particular, is known for relying on the package cache
for code analysis.
On my local machine, `lint.bash` produces the following output:
```
cmd/dep/godep_importer_test.go:108: github.com/golang/dep/internal/test.Writer composite literal uses unkeyed fields
exit status 1
internal/gps/manager_test.go:48: github.com/golang/dep/internal/test.Writer composite literal uses unkeyed fields
internal/gps/manager_test.go:69: github.com/golang/dep/internal/test.Writer composite literal uses unkeyed fields
internal/gps/manager_test.go:91: github.com/golang/dep/internal/test.Writer composite literal uses unkeyed fields
internal/gps/manager_test.go:147: github.com/golang/dep/internal/test.Writer composite literal uses unkeyed fields
internal/gps/result_test.go:129: …
```

Build all packages before running linters

---

internal/gps/source_manager.go

The work being done here is already guarded by an atomic. This code
appears very confused, but perhaps it is I who is confused.
Simplifies existing code.
I dunno; this might be subtle.
No.
None.

gps: simplify shutdown cleanup

---

.travis.yml
cmd/dep/ensure.go
context.go
hack/lint.bash
internal/gps/bridge.go
internal/gps/cmd.go
internal/gps/pkgtree/pkgtree_test.go
internal/gps/selection.go
internal/gps/solve_basic_test.go
internal/gps/solve_failures.go
internal/gps/source_manager.go
internal/gps/typed_radix.go
internal/gps/vcs_repo.go
internal/gps/vcs_repo_test.go
internal/gps/vcs_source.go
internal/gps/vcs_source_test.go
internal/gps/version.go
internal/gps/version_queue_test.go
internal/test/integration/testproj.go
internal/test/test.go

Removes a bunch of dead code and fixes minor bugs.
N/A.
No.
None that I know of.

Add static checkers

---

internal/gps/identifier.go
internal/gps/manager_test.go
internal/gps/satisfy.go
internal/gps/selection.go
internal/gps/solve_basic_test.go
internal/gps/solve_bimodal_test.go
internal/gps/solve_failures.go
internal/gps/solve_test.go
internal/gps/solver.go
internal/gps/source.go
internal/gps/strings.go

This introduces a new satisfiability check in the solver that ensures we don't have any import paths that vary only by path. It's actually really just `ProjectRoots`, not import paths as a whole, because internal package paths are implicitly verified to be the right case by the package existence checker - that's grounded in the reality of a case-sensitive comparison against what's been read from disk and built into the `PackageTree`.
The effect of this is that dep will only allow one case-variant of any given import path in a solution/a `Gopkg.lock`. It will search until it finds combinations of versions of projects that maintain this invariant - as well as all other satisfiability criteria, like version constraints - or fail out with an informative message if no such combination exists. …

Add satisfiability check for case variants

---

context_test.go
internal/gps/result_test.go
test_project_context_test.go
txn_writer_test.go

This change replaces global discard `Logger` variables with per-test instances.
We've developed a habit of using consolidated global vars to share `discardLogger`s between tests (`log.New(ioutil.Discard, "", 0)`).  This seems logical since calls are effectively no-ops, _but_ the internals of the `Logger` are still locking to serialize writes to `ioutil.Discard`, which creates unnecessary coupling and synchronization between tests that could otherwise be completely independent and/or parallel.

testing: de-globalize discard loggers

---

internal/gps/source_cache_multi.go
internal/gps/source_cache_test.go

This PR adds `type multiCache struct`, which is a `singleSourceCache` that manages two cache levels, ephemeral in-memory and persistent on-disk.  It is currently only tested, and will be integrated later.
This is a simple implementation.  There is room for optimization which can be explored later when integrating (e.g. I've implemented async background disk writes on my WIP branch, which pairs nicely with batch Bolt updates, especially now that we're using a single file).
Towards #431

gps: source cache: adding multiCache

---

internal/gps/cmd.go
internal/gps/cmd_unix.go
internal/gps/cmd_windows.go
internal/gps/vcs_source.go

Includes a command's stderr in the error string. I was seeing SSL errors with one of my dependencies, and the missing error information was quite annoying.
Nothing special.
No.
None.

gps: include output in error

---

internal/gps/deduce.go
internal/gps/deduce_test.go
internal/gps/maybe_source.go
internal/gps/solve_basic_test.go
internal/gps/source_manager.go

This exposes all possible source URLs that are deduced for a given import path.
This PR was created to accommodate https://github.com/golang/dep/pull/1149 (`gvt` importer), following @sdboyer 's advice.
`gvt` allows the user to specify an alternate url (e.g. fork) for a vendored import, via the `Repository` field in the manifest. However, all packages that are listed in the manifest have the `Repository` field even if it points to the original source URL. 
`gps` already has a complex logic of deducing the source URLs given an import, however the actual URLs are not exposed to the callers of SourceManager. The new exported `SourceURLsForPath()` will allow the importers to understand if the a URL is a not a default one, and only in such a case, pass it as a constraint.
This change required …

add SourceURLsForPath() to SourceManager ineterface

---

context.go

The error when code isn't "in" a GOPATH is a bit confusing, as what we really mean is "not under `GOPATH/src`". this updates those errors to reflect that.
wording - it's always fun
nope
fixes #1182

ctx: improve "not under GOPATH" errors

---

cmd/dep/status.go
cmd/dep/status_test.go

This change adds concurrent BasicStatus creation, maintaining the order
of status output.
It reduces the time taken by `status`.
Before:
```
real    0m16.092s
user    0m0.408s
sys    0m0.394s
```
After:
```
real    0m1.777s
user    0m0.411s
sys    0m0.339s
```
Correctness of concurrency code.
~Some help with the detected race condition.~
Related to https://github.com/golang/dep/issues/1008 , making status more verbose on failures.

fix(status): concurrent BasicStatus creation

---

internal/gps/cmd_unix.go

Instead, we use the existing `waitDone` channel to wait for the
command to return and then clean up the timer unconditionally. This
may hold the goroutine open for longer than strictly necessary, but
that seems harmless.
Closes #1194.
@jmank88

gps: avoid race condition in variable assignment

---

cmd/dep/ensure.go
cmd/dep/ensure_test.go

Performs `ensure -update` arguments validation concurrently.
Related to TODOs:
* [TODO(sdboyer) do these concurrently](https://github.com/golang/dep/blob/master/cmd/dep/ensure.go#L352)
* [TODO(sdboyer) return all errors, not just the first one we encounter](https://github.com/golang/dep/blob/master/cmd/dep/ensure.go#L355)
Concurrent code implementation.

fix(ensure): concurrent update args validation

---

internal/gps/prune.go
internal/gps/prune_test.go
internal/gps/strip_vendor.go
internal/gps/strip_vendor_windows.go

Add different functions to `gps` that implement different pruning modes.
The different modes are as follows:
* `pruneNestedVendorDirs`: Delete any directory named `vendor`.
* `pruneNonGoFiles`: Delete any file that doesn't end with `.go` (will keep files matching common names for legal documents)
* `pruneGoTestFiles`: Prune Go test files (any file ending with `_test.go`)
* `pruneUnusedPackages`: Delete all files in unused Go packages. Since we might import a sub package we only delete files and keep directories.
Correctness.
Refer to https://github.com/sgotti/glide-vc/ for comparison and ideas.
Is adding an option to allow overriding deletion of specific files a good idea?
Breaking down #952

internal/gps: Add prune functions to gps

---

context.go
context_test.go
internal/fs/fs.go
internal/fs/fs_test.go
project.go
project_test.go

This checks the manifest and lock file name on case insensitive systems to ensure that the case exactly matches `Gopkg.toml` and `Gopkg.lock`.
Looking for feedback on the tests and added functions.
fixes #1035
- `fs`
- Export `IsCaseSensitiveFilesystem`. Add and run test on windows, linux.
- Add function `ReadActualFilenames` to read actual file names of given
string slice. Add tests to be run on windows.
- `project`
- Add function `checkCfgFilenames` to check the filenames for manifest
and lock have the expected case. Use `fs#IsCaseSensitiveFilesystem`
for an early return as the check is costly. Add test to be run on windows.
- `context`
- Call `project#checkCfgFilenames` after resolving project root. Add test
for invalid manifest file name to be run on windows.

check Gopkg filenames case on case insensitive systems

---

hack/lint.bash
internal/gps/vcs_source.go

This PR fixes `./hack/lint.bash` failures, by directly returning errors and ~removing~ ignoring unused functions/types from `prune.go`.
Should the errors be wrapped?

gps: ./hack/lint.bash fixes

---

internal/gps/vcs_source.go
internal/gps/vcs_source_test.go

`func (s *gitSource) listVersions` can return duplicate mappings (same tag to multiple revisions), and we were dependent on both the order of the slice elements and the implementation details of `func (c *singleSourceCacheMemory) setVersionMap` to de-dupe what actually get's used (the cache stores a `map` internally, so the _last_ element is the one that wins).
This PR changes the way the list is built, so that duplicates are replaced.

gps: vcs: dedupe git version list

---

internal/gps/pkgtree/pkgtree.go

This PR adds a check for the incoming err argument of this walkFn, in response to a recent change on tip.
Fixes #1220

pkgtree: add os.IsPermission check for walkFn err arg

---

CHANGELOG.md
cmd/dep/ensure.go

This change makes `ensure -add` concurrently add the dependencies ~and
uses golang.org/x/sync/syncmap for a concurrent map to replace
addInstructions map~.
Also, logs a message when the sources are being fetched.
```
$ dep ensure -v -add github.com/darkowlzz/openurl
Fetching sources...
(1/1) github.com/darkowlzz/openurl
Root project is "github.com/darkowlzz/depfoo"
```
Sources are enumerated only in verbose mode.
Related to TODOs:
[TODO(sdboyer) return all errors, not just the first one we encounter](https://github.com/golang/dep/blob/v0.3.1/cmd/dep/ensure.go#L498)
[TODO(sdboyer) do these concurrently?](https://github.com/golang/dep/blob/v0.3.1/cmd/dep/ensure.go#L499)
Concurrency code ~and the usage of syncmap~.
No.
fixes #1202

Concurrent ensure add

---

cmd/dep/main.go
context.go
internal/gps/source_manager.go

* Add DisableLocking bool members to Ctx and gps.SourceManagerConfig structs.
This effectively communicates DEPNOLOCK from the shell, to Ctx, to
SourceManager.
The member is named DisableLocking to make its zero-value useful.
* Add Locker interface which implements TryLock(), Unlock(), and GetOwner()
which lockfile.Lockfile alredy adheres to.  This interface replaces the new
type for the lf member of the SourceMgr struct.
* Add a FalseLocker type which adheres to the Locker interface which does
nothing.
* Conditionally set the lf member of SourceMgr to either an instance of
lockfile.Lockfile or FalseLocker depending on the value of
SourceManagerConfig.DisableLocking.
This pull request adds functionality that checks the DEPNOLOCK environment variable to determine if session manager should …

[WIP] Feature to disable file locking when DEPNOLOCK set

---

internal/gps/source.go
internal/gps/source_cache.go
internal/gps/source_cache_bolt.go
internal/gps/source_cache_bolt_test.go
internal/gps/source_cache_multi.go
internal/gps/source_cache_test.go
internal/gps/source_test.go

This PR optimizes `singleSourceCacheMemory.getAllVersions()`, fixes a bug, and clears up an error-prone `len(0)` v.s. `nil` slice distinction.
This is the optimization that exposed the bug fixed in #1212, ~and is blocked by that change (but putting it up now provides some context).~ Edit: Unblocked.
Related to #431

gps: source cache: memory cache optimization

---

internal/gps/solve_failures.go

Fixes a bad error message added in dep 0.3.1.
Previously, errors like the following could occur:
v0.4.2: Could not introduce github.com/sirupsen/logrus due to a case-only variation: it depends on "github.com/Sirupsen/logrus", but "github.com/evalphobia/logrus_sentry@v0.4.2" was already established as the case variant for that project root by the following other dependers:
(root)
github.com/docker/docker@8510adf8c856d6f0871650216a0e1d7e6ece46ee
This fix matches the correct behavior when there is only one depender earlier in
the function.
Is there an opportunity to add a test for this? I didn't see one.
No
I didn't file an issue but I did jot down a comment on the PR that introduced this issue: https://github.com/golang/dep/pull/1079#discussion_r141989727

internal/gps: fix case mismatch error with multiple dependers

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md

Adds instructions about updating changelog in the PR template.
The instruction message and format.
Is this good or can it be improved?

pr-template: instruction about updating changelog

---

CONTRIBUTING.md

Updates the contributing docs.
It's confusing that when preparing a PR that updates dependencies, you suddenly get a lot of untracked files.
Make sure I'm not wrong.
No.
None.

CONTRIBUTING.md: Document need to run dep prune

---

cmd/dep/integration_test.go
internal/test/integration/testproj.go

This PR drops an unused parameter from an integration test function.  It used to affect some special case `GOPATH` manipulation for CI which was removed.

integration tests: remove unused parameter

---

cmd/dep/status.go

Moves lockfile check before `runStatusAll()`.
¯\_(ツ)_/¯
No.
fixes #1232

fix(status): check lockfile before runStatusAll()

---

internal/gps/_testdata/src/canon_confl/a.go
internal/gps/_testdata/src/canon_confl/b.go
internal/gps/_testdata/src/canonical/main.go
internal/gps/_testdata/src/canonical/sub/sub.go
internal/gps/identifier.go
internal/gps/pkgtree/pkgtree.go
internal/gps/pkgtree/pkgtree_test.go

This adds capability to pkgtree to extract canonical import path comments from the packages. That will later be used as additional constraints when solving the dependencies (will come in a separate PR).
(And a couple unrelated typo fixes and code cleanups along the way)
I was wondering, at the very end of `ListPackages`, where the [package gets added to the `Packages` map](https://github.com/golang/dep/blob/master/internal/gps/pkgtree/pkgtree.go#L180), should I also add a copy with a canonical path key like blow? So that solver could see both versions available?
```go
if pkg.CommentPath != "" {
ptree.Packages[pkg.CommentPath] = PackageOrErr{
P: pkg,
}
}
```
Also, is there a way to develop from my fork? Can't even get tests running:
```
$ go test $(go list ./internal/gps/pkgtree/...) …
```

[WIP] Respect canonical import comments

---

CONTRIBUTING.md

Updates the contributing docs. 
Because there seems to be no description about `board` in README.
Make sure I'm not wrong.
No.
None.

Remove link of `board`

---

internal/gps/vcs_repo.go
internal/gps/vcs_repo_test.go

This PR refactors `newVcsRemoteErrorOr` and `newVcsLocalErrorOr` with the primary goal of fixing the bug of wrapping the error passed in and a secondary goal of drying up the usages.
Should we still wrap up the context errors, rather than return them bare?
There is a `case context.Canceled, context.DeadlineExceeded:` check for log suppression, otherwise I'm not sure the err *needs* to be bare.

gps: vcs repo error fix

---

internal/gps/cmd_unix.go
internal/gps/source_manager.go

This has two parts - first, we break the context connection from the incoming ctx to a `cmd`, such that its cancellation does not immediately propagate to the `exec.ContextCommand`, resulting in an immediate `os.Process.Kill()` (which we want to avoid).
In testing this, though, i discovered that the signals sent via ctrl-C were still being processed immediately by the e.g. git subprocesses. So, after tearing my hair out for a while, I discovered that it's because ctrl-C from a terminal, by default, [sends the signal to everything in the process _group_, and (with default settings) our spawned subprocesses are placed in that same group](https://stackoverflow.com/a/35435038).
This is a bit of just rearranging deck chairs as it still has the same effect, but I prefer to be more explicit …

Break context chain and move subprocesses into separate pgroups

---

CONTRIBUTING.md

CONTRIBUTING.md cannot resolve below links.
Please confirm these are correct links on browser.
https://github.com/budougumi0617/dep/blob/fix-unresoleved-link-in-markdown/CONTRIBUTING.md
Please tell me when I make a mistake
None.

Fix unresolved link in CONTRIBUTING.md

---

CHANGELOG.md

I forgot to add this in the PR directly but it's been merged and will be part of 0.3.2.

List import support for gb/gvt in the changelog

---

internal/gps/cmd_unix.go

This PR removes an extra command context and switches to use Cmd.Process.Kill() directly, rather than indirectly triggering the kill via cancelling the context.
Follow up from #1270.

gps: cmd_unix: remove extra command context; use Cmd.Process.Kill() directly

---

internal/gps/manager_test.go
internal/gps/source_cache_bolt_test.go
internal/gps/source_cache_test.go
internal/gps/vcs_source_test.go
internal/gps/vcs_version_test.go

This PR parallelizes a bunch of gps tests (I roughly targeted ones running `>100ms` and ignored `<100ms`), and reduces the running time of `go test ./internal/gps` on my machine from `~43s` to `~31s`.

gps: parallelize many tests

---

.travis.yml
CHANGELOG.md
hack/build-all.bash

The [release](https://github.com/golang/dep/releases/tag/v0.3.2) tab on github has links to windows binaries. These links are named wrongly. After downloading, I have to rename `dep-windows-amd64` into `dep-windows-amd64.exe` in order to use the binary.
Releases targeting Windows should have a .exe suffix.
fixes  #1291

Releases targeting Windows now have a `.exe` suffix

---

txn_writer.go

If the txn writer leaves a `vendor.orig` directory behind, subsequent runs will barf on it - #1304.
While there's more work to be done in making all of this safe in the event of a signal being sent to dep, this change at least means that if a signal is sent during the rename and a .vendor.orig directory is left behind, subsequent runs will treat its contents as ignored.
Fixes #1304

dep: Use hidden tempdir for old vendor

---

cmd/dep/root_analyzer.go

Provides some output during dep init to help soften the user experience where people think the tool is hanging. 
For now this WIP PR is just to start the discussion of how to bring back functionality similar to what was added before in.
https://github.com/golang/dep/pull/194/files#diff-b14a2eb16f1efbc6aa9f1ffdad724265R241
Yes. For now I just have something very rudimentary that displays when a new direct dep found. To regain functionality from #194 there also needs to be output when transitive deps are discovered. I believed this should be done in `s.Solve()`. Still digging in.
fixes #1144 
**DEMO**
```
dep init
HEAD is now at 6a17370 Removing godeps for testing without godep init
Cached github.com/emicklei/go-restful
Cached github.com/go-kit/kit
Cached github.com/stretchr/testify
Cached …
```

Adding UX output to dep init

---

CHANGELOG.md

I forgot to include this in the PR directly. 😊

Include #1176 in the changelog

---

docs/FAQ.md

Updates the FAQ section on 'Best Practices' for usage in a CI environment.
Preview link - [sudo-suhas/dep:docs/FAQ.md@`b92d0e7`#how-do-i-use-dep-in-ci](https://github.com/sudo-suhas/dep/blob/b92d0e7ae6cef7eac13276fbae1bcafff166fbca/docs/FAQ.md#how-do-i-use-dep-in-ci)
Not 100% sure about the usage of `env` in travis config. Would it be better to inline the `X.X.X` in the `curl` command itself?
Should there be an example for appveyor as well? I am not quite sure how we would do this in appveyor though.
fixes #1275
P.S I also made some formatting change for the Docker section to leverage the syntax highlighting in github/editors like vscode.

update Best Practices FAQ for usage in CI

---

cmd/dep/ensure.go
cmd/dep/init.go
internal/gps/bridge.go
internal/gps/manager_test.go
internal/gps/solve_test.go
internal/gps/solver.go
internal/gps/source_manager.go

The solver itself needs to be able to take a context, so that it can abort. It also needs to be able to handle cases where its underlying `SourceManager` gets released. Strictly speaking, these two cases are separate, but it makes enough sense to deal with them in one PR, just because there's so many overlapping bits to think about.
this rejiggers a bunch of stuff in the solver itself, and my preliminary passes have definitely produced test failures, so correctness concerns here.
it's work towards #160 and #423, but doesn't itself square those away entirely.
fixes #1060

Plumb context through solver

---

internal/gps/manager_test.go
internal/gps/source_cache_bolt_test.go
internal/gps/source_cache_test.go
internal/gps/vcs_source_test.go
internal/gps/vcs_version_test.go

Revert the test parallelizations, as appveyor doesn't seem to be able to handle it.
i really want us to be able to do these things, but these are causing other PRs to erroneously fail just...all the time. really need that local repo swap-in solution. 🤔

Deparallelize tests

---

CHANGELOG.md
internal/gps/manager_test.go
internal/gps/maybe_source.go
internal/gps/source_manager.go
internal/gps/vcs_source.go
internal/gps/vcs_source_test.go

Instead of forcing the user to clean up dirty git repositories, we can
take at least basic steps to doing it ourselves - or, if we detect
problems, instructing the user to fix it.
The overhead introduced here is a `git status` call, which will be
non-negligible on larger repos, but it's probably worth it for the
resilient behavior.
Eventually, once we get to #534, we'll want to issue a warning when we undertake a cleanup.
This needs tests. Also, let's delay merging this until after the next release so that it can percolate on tip for a while.
Might want to also refactor `maybeGitSource.try()` to do this check earlier, and `os.RemoveAll()` then try again if it doesn't work.
Possible failure modes. It'd be great if this attempt at making things better didn't inadvertently make things worse! …

gps: Adaptively clean dirty git repos

---

cmd/dep/dep_test.go

Trying to fix the breaking tests on go:tip due to the introduction of GOCACHE.
Refer: golang/go@5e35954
More info on GOCACHE: https://groups.google.com/forum/#!topic/golang-dev/qfa3mHN4ZPAs
Fixes #1368

Disable GOCACHE in test

---

docs/FAQ.md

This updates the FAQ section for `dep` usage in CI for caching. It mentions the caveats as noted by @carolynvs in https://github.com/golang/dep/pull/1293#issuecomment-342969292 and the travis config snippet for enabling it.
Is there any change required in the wording? 
Are there any other caveats that are worth mentioning?
None.
Preview link - [sudo-suhas/dep:docs/FAQ.md@`docs-faq-ci-caching`#how-do-i-use-dep-in-ci](https://github.com/sudo-suhas/dep/blob/docs-faq-ci-caching/docs/FAQ.md#how-do-i-use-dep-in-ci)

update FAQ CI usage section for caching caveats

---

CHANGELOG.md
gps/vcs_repo.go
gps/vcs_source_test.go

This change suppresses git password prompts in more places. Cherry picked from #1250 (https://github.com/golang/dep/pull/1250/commits/f1f0bac72043f48decc01e93c642b9900c2b0c98).
It might fix: #1356

gps: vcs: suppress git password prompts

---

gps/source_test.go
gps/vcs_source.go
gps/vcs_source_test.go

`git ls-remote` was being run without a current working directory, which - for some versions of git - has the unfortunate side effect of still looking for a local `.git` in the cwd hierarchy, and failing if that .git is a file instead of a directory (as it might be if the user is working beneath a git submodule).
This relocates the call to somewhere safer, under gps' control, so that we've a better (though not foolproof) guarantee of not colliding with a `.git` file.
Fixes #1338.

gps: Insulate against .git as file

---

CHANGELOG.md
gps/vcs_source.go

This should fix panics for cases where `git ls-remote` contains
unepxected lines (e.x. some extra warnings from ssh)
Related to #1379
This should add some sanity checks for `git ls-remote` output.
fixes #1379 
fixes #1209

Add a sanity check for git ls-remote output

---

cmd/dep/init.go
cmd/dep/testdata/harness_tests/init/manifest-exists/testcase.json
gps/prune.go

In some places, we were assuming that the error returned from another call was already wrapped with a clear error message. These extra wraps make it clear that init failed, even when solve
may have printed messages that made people think that everything succeeded.
Make sure the error messages clearly indicate that init failed.
Nope.
Fixes #1196

cmd/dep: wrap errors returned from init

---

Gopkg.toml
analyzer_test.go
gps/prune.go
hack/lint.bash
manifest.go
manifest_test.go

Add prune options to `dep.Manifest`.
WIP:
Generic review.
How should prune options be defined for projects? 
Here is a list of suggestions:
1. TOML table under prune:
```toml
[prune]
non-go = true
unused-packages = true
["github.com/golang/protobuf"]
non-go = true
go-tests = true
```
2. `prune` table under constraints (what about overrides?)
```toml
[[constraint]]
name = "github.com/jmank88/nuts"
version = "0.2.0"
prune = { non-go = true, go-tests = true, unused-packages = true }
```
or 
```toml
[[constraint]]
name = "github.com/jmank88/nuts"
version = "0.2.0"
[constraint.prune]
go-tests = true
unused-packages = true
```
One more step towards #944

Add prune options to manifest

---

CHANGELOG.md
gps/vcs_source.go
gps/vcs_source_test.go

When v0 is requested, and there are no semver branches/tags, fallback to the master branch.
See http://labix.org/gopkg.in#VersionZero
Nope.
Nope.
Fixes #933 
Fixes #776

gps: fix panic for gopkgin's implicit v0

---

testdata/txn_writer/expected_manifest.toml
txn_writer.go

The Gopkg.toml file is always generated with an empty line as the first line.
It's not a big deal, but I find it kind of annoying, so I removed it.
Tests were very slow and failed on apparently unrelated things... if it fails here as well I might need to investigate it further.

removed first empty line on the example file

---

CHANGELOG.md
internal/fs/fs.go

When copying files, directly check for errors when closing
the destination file rather than using out.Sync() with
a deferred Close().
The out.Sync() call can be incredibly expensive on systems which
are I/O-heavy, yet may have more than ample memory and CPU
resources.  As part of a file copy, we only need to ensure that
errors writing and closing the file handle are checked and dealt
with, rather than forcing the entire copied file to physical storage.
Environments such as Continuous Integration servers and container
hosts are often I/O-heavy.  In such environments, this change
can make a significant difference - milliseconds vs minutes.
Avoid unnecessarily syncing newly copied files to physical storage.
A sync to physical disk imposes heavy latency on completing the file copy, and it is …

internal/fs: Don't Sync() destination file after copy

---

cmd/dep/status.go

collectConstraints(), used by `dep status`, was trying to do on-the-fly
conversions of existing tools. That needs to remain disabled until we
also turn it on for `dep init` and `dep ensure`.

dep: Skip tool conversions in dep status

---

CHANGELOG.md
cmd/dep/testdata/harness_tests/init/glide/case1/final/Gopkg.lock
cmd/dep/testdata/harness_tests/init/glide/case1/final/Gopkg.toml
cmd/dep/testdata/harness_tests/init/gvt/case1/final/Gopkg.lock
cmd/dep/testdata/harness_tests/init/gvt/case1/final/Gopkg.toml
internal/importers/base/importer.go
internal/importers/base/importer_test.go
internal/importers/glide/importer_test.go
internal/importers/glide/testdata/golden.txt
internal/importers/govendor/importer_test.go
internal/importers/gvt/importer_test.go
internal/importers/gvt/testdata/golden.txt

This PR changes how empty constraints are handled. 
An empty constraint is defined as having no branch, version, revision or source other than default. 
If this is the case, the import is skipped and an entry is **not** added to manifest, nor is it added to the lock.
Assuming that the logic in `internal/importers/base/importer.go` is sufficient, changes to the tests (specifically `tag lock hints Lock to tagged revision`).
Do we also want to omit the lock entry?
fixes #1373

Skip empty constraints

---

context_test.go
manifest.go
manifest_test.go

Constraints/Overrides configs should have a version rule or source.
Warn when it doesn't. 
ex.
```
[[constraint]]
name = "github.com/JackyChiu/super-cool-project
$ dep ensure
dep: WARNING: version rule or source should be provided in "constraint"
```
- Is the warning message clear?
fixes #1336

Manifest Version/Source Validation

---

docs/FAQ.md
docs/Gopkg.toml.md

Documentation for prune options in `Gopkg.toml`. The current code is in #1219.
Last step in #944 :grin:

Add documentation about prune to Gopkg.toml docs

---

.travis.yml

This commit manually instructs Travis to add `github.com` to `~/.ssh/known_hosts`. It looks like this was not added to the new build images.
Builds should pass on newer Travis builds.
fixes #1428

Add Github to known_hosts

---

gps/cmd_unix.go

All command errors current lack output context - stderr, stdout, anything. we basically only get exit codes, and it's very hard to know what's going on. This is the simplest possible thing that could work - just dump it all back into a string.
This is really gross, and i'm kind of ashamed of it, and we desperately need to get around to better nested error handling.

Restore output context to (git) errors

---

docs/FAQ.md
docs/Gopkg.toml.md

This reverts commit b741887298d080f018512c26364b382bd13e89fe, reversing changes made to 8f4a82cb39ca7bf4e64b5c37e7ad5e9280c3fa18.
Until we have #1369, doc changes should be merged immediately before a release. Too soon and people see docs for unreleased changes.
Before we do our next release, we should add these docs back in.

Revert "Merge pull request #1405 from ibrasho-forks/prune-docs"

---

docs/FAQ.md
docs/Gopkg.toml.md

This reverts #1451 which reverted the prune-docs.
It should be merged after #1219 is merged to master.
/cc @carolynvs @sdboyer

Restore prune docs

---

cmd/dep/status.go
cmd/dep/status_test.go

It makes `collectConstraints()` concurrent. We need this to reduce the running time of status, which increased recently to ~30s due to introduction of `collectConstraints()`. This change brings the time down to ~5s.
Verbose output shows constraints collection progress:
```
$ dep status -v
Collecting project constraints:
(1/15) github.com/Masterminds/semver
(2/15) github.com/Masterminds/vcs
(3/15) github.com/armon/go-radix
(4/15) github.com/boltdb/bolt
....
(12/15) github.com/sdboyer/constext
(13/15) golang.org/x/net
(14/15) golang.org/x/sync
(15/15) golang.org/x/sys
Checking upstream projects:
(1/15) github.com/Masterminds/semver
(2/15) github.com/Masterminds/vcs
(3/15) github.com/armon/go-radix
(4/15) github.com/boltdb/bolt
....
```
Concurrency implementation.
Should we return errors in …

status: make collectConstraints() concurrent

---

cmd/dep/status.go
cmd/dep/status_test.go

Adds flags validation to status command. The validation is based on 2 types of flags:
Operating mode flags: ~-detailed, -modified,  -unused~, `-missing, -old`
Output format flags: `-json, -dot, -f`
`-dot` format flag is applicable only to the default status mode.
Validation logic.
No.
None. But preparing for the upcoming different status operating mode implementation.

status: add validateFlags()

---

cmd/dep/status.go

This changes fixes a bug due to which the LATEST field in status was
missing for projects that were not in manifest but in lock and had
pairedVersion.
Since we check `bs.Version` to not be nil before entering into
updateability block, we can use the same value as the constraint for
matching with the version list obtained for the projects.
Impact of this change in other part of the code.
Fixes #1462

status: use unpaired ver constr when checking updateability

---

docs/FAQ.md

Removes a duplicate word in the FAQ.

docs: fix typo

---

cmd/dep/init.go
cmd/dep/testdata/harness_tests/ensure/add/all-new-double-spec/final/Gopkg.toml
cmd/dep/testdata/harness_tests/ensure/add/all-new-double/final/Gopkg.toml
cmd/dep/testdata/harness_tests/ensure/add/all-new-spec/final/Gopkg.toml
cmd/dep/testdata/harness_tests/ensure/add/all-new/final/Gopkg.toml
cmd/dep/testdata/harness_tests/ensure/add/errs/double-diff-spec/final/Gopkg.toml
cmd/dep/testdata/harness_tests/ensure/add/errs/self-add/case2/final/Gopkg.toml
cmd/dep/testdata/harness_tests/ensure/empty/case1/final/Gopkg.toml
cmd/dep/testdata/harness_tests/ensure/pkg-errors/case1/final/Gopkg.toml
cmd/dep/testdata/harness_tests/init/case1/final/Gopkg.toml
cmd/dep/testdata/harness_tests/init/case2/final/Gopkg.toml
cmd/dep/testdata/harness_tests/init/case3/final/Gopkg.toml
cmd/dep/testdata/harness_tests/init/case4/final/Gopkg.toml
cmd/dep/testdata/harness_tests/init/glide/case1/final/Gopkg.toml
cmd/dep/testdata/harness_tests/init/glide/case2/final/Gopkg.toml
cmd/dep/testdata/harness_tests/init/glide/case3/final/Gopkg.toml
cmd/dep/testdata/harness_tests/init/glock/case1/final/Gopkg.toml
cmd/dep/testdata/harness_tests/init/godep/case1/final/Gopkg.toml
cmd/dep/testdata/harness_tests/init/govend/case1/final/Gopkg.toml
cmd/dep/testdata/harness_tests/init/govendor/case1/final/Gopkg.toml
cmd/dep/testdata/harness_tests/init/gvt/case1/final/Gopkg.toml
cmd/dep/testdata/harness_tests/init/relative_path/final/project_dir/Gopkg.toml
cmd/dep/testdata/harness_tests/init/skip-hidden/final/Gopkg.toml
cmd/dep/testdata/harness_tests/init/vndr/case1/final/Gopkg.toml
manifest.go
manifest_test.go
testdata/txn_writer/expected_manifest.toml
txn_writer.go

- Adds default prune options on `init`
- Updates example comment in manifest to include default prune settings
- How defaults are set in `init.go`
- The examples comment in `txn_writer.go`
Do we need tests for `toRawPruneOptions`?
fixes #1404

Add default prune options for init cmd

---

cmd/dep/init.go

Use the default prune options set on the manifest to immediately prune vendor when it is written.
Follow-on to #1460.
/cc @arbourd

cmd/dep: apply default prune options on init

---

cmd/dep/status.go
cmd/dep/status_test.go

Fixes projectConstraint sorting order on the status command.
fixes #1482

Fixed sorting order and reorder test

---

CHANGELOG.md
cmd/dep/ensure.go
cmd/dep/ensure_test.go

Details use of '-v' command line option in the ensure sub command.
Look for the updated command line option syntax and an associated test case.
No
Fixes #1458

Add optional '-v' flag to ensure args help text

---

cmd/dep/status.go
cmd/dep/status_test.go

Makes the [`collectConstraints`](https://github.com/golang/dep/blob/5b317da10a7d7a7470d12ef1f8a5fcc592d0238b/cmd/dep/status.go#L751) method collection only applicable constraints (constraints that are actually imported in the project). Does so by checking project constraints against direct deps.  
Implementation improvements
fixes #1409

Collect Applicable Constraints

---

cmd/dep/status_test.go
cmd/dep/testdata/status/collect_constraints/main.go

Made a `testdata` dir and test file for `TestCollectConstaints`. 
Forgot to include this in #1480

Collect Applicable Constraints - Test Cleanup

---

cmd/dep/gopath_scanner.go

When the -gopath flag is used with dep init, it currently displays the error message that `Following dependencies were not found in GOPATH` when the VCS info returns an error, even if the dependency actually exists in the GOPATH. Showing the user which project roots didn't exist and which ones existed but had problematic version info would lead to less confusion. 
I wasn't sure of the best way to go about doing this. Basically, in the `scanGopathForDependencies` method, there it is checking `g.ctx.AbsForImport` and `gps.VCSVersion` which both end up setting notondisk[pr] for that item. The errors from gps.VCSVersion don't really mean that that the root was not on disk, but rather the VCS info had an error. I didn't want to mess with notondisk so I created another map to keep track of …

Improve error message when gopath dependency exists but lacks VCS

---

Gopkg.lock
Gopkg.toml
vendor/github.com/jmank88/nuts/Gopkg.lock
vendor/github.com/jmank88/nuts/Gopkg.toml
vendor/github.com/jmank88/nuts/paths_test.go

Upgrades `github.com/jmank88/nuts` to 0.3.0. Reacting to https://github.com/jmank88/nuts/issues/2.

upgrade github.com/jmank88/nuts to 0.3.0

---

gps/solution_test.go
gps/vcs_source_test.go

Some bzr tests are on broken on appveyor.
The precise underlying causes of the problem with bzr on Windows is
unclear - it could be just about bzr with Windows, or the version of
bzr, or some underlying system interaction. But it's causing appveyor
tests to erroneously fail, and bzr is so little-used that it's
acceptable to just skip the tests, for now.

gps: Disable certain bzr tests on Windows

---

gps/deduce.go
gps/deduce_test.go
gps/source_manager.go

Rebase of https://github.com/golang/dep/pull/1160

Rearrange path validation to allow ports

---

internal/importers/base/importer.go
internal/importers/base/importer_test.go
internal/importers/govendor/importer_test.go
internal/importers/importertest/testcase.go

I missed this when I reviewed #1414 but it introduced a misleading log messages that needs to be corrected.
* Remove warning when the constraint hint is empty. It's a common case and the lock may still be imported.
* Fix warning to say lock instead of constraint when the lock hint cannot be resolved.

Tweak import warnings to prevent confusion

---

docs/FAQ.md

Resolves an incorrect example in the FAQ docs.
Make sure the new dependency upgrade order matches the algorithm described above it, as well as the tests.
I don't think so, thanks!
Fixes #1528.

Fix dependency upgrade example in FAQ.md

---

cmd/dep/testdata/harness_tests/status/case1/table/stdout.txt
cmd/dep/testdata/harness_tests/status/override_constraint/stdout.txt
cmd/dep/testdata/harness_tests/status/revision_constraint/stdout.txt
gps/paths/paths_test.go
gps/pkgtree/pkgtree_test.go
internal/feedback/feedback_test.go

This allows people to run `go test ./... -update` (which used to work but must have gotten broken at some point). Without this, in order to do a mass update of golden files, you need to run the update against individual packages which is a huge pain.
While I was in there, I also updated the golden files for status. They always show as modified when I update all the tests, but I'm pretty sure they don't fail in CI because it's just trailing whitespace.
Nothing
Nope
None

Make it easier to update all golden files at once

---

CHANGELOG.md
manifest.go
manifest_test.go

Per-project prune option handling is broken in v0.4.0. This PR fixes the handling and add corresponding
tests.
Fixes #1561

Fix ignored per-project prune options (#1561)

---

CHANGELOG.md
cmd/dep/init.go
cmd/dep/prune.go
gps/prune.go
gps/prune_test.go
gps/solution.go
gps/solution_test.go
manifest.go
manifest_test.go
testdata/manifest/golden.toml
txn_writer.go
txn_writer_test.go
website/blog/2018-01-23-announce-v0.4.0.md

We don't actually honor per-project prune options correctly.
This new type defers computation of the actual prune value for a given project until the method is called, rather than trying to precompute it. By deferring computation, we retain full fidelity on the original cascading inputs.
This is an emergency fix, so i'm pushing it through fast.
fixes #1561

Honor per-project prune options correctly

---

website/blog/2018-01-23-announce-v0.4.0.md

It's still pointing to v0.4.0 release notes, which contains that prune bug.

Update release notes link in v0.4.1 blog post

---

CHANGELOG.md

Issue references were missing closing parentheses, this fixes that. Will also need to update [the release description](https://github.com/golang/dep/releases/tag/v0.4.0).

Fix formatting of issue references in v0.4.0 changelog

---

docs/FAQ.md

FAQ index links to headers containing `'` are parsed to `-` when the FAQ page is generated. This PR changes the links in the index to follow this.

Fix link in FAQ to bullets containing '

---

.gitignore
hack/build-all.bash

This change has a few simple improvements to the bash build script, such as ensuring that you're in the root of the repo, to ensure it will work. It also encloses all variable calls in curly brackets, and adds the `release/` output dir to the gitignore.
I was cleaning this up as a knock on to https://github.com/Homebrew/homebrew-core/pull/23360 so that users of homebrew can get full version information.
This should have no functional change.
Nope!
None

Fixes and cleanup to build script

---

CONTRIBUTING.md

Fixed that the explanation was described to execute `dep prune` when `Gopkg.toml` was updated. 
Because now it is no longer necessary to manually run `dep prune`.

Remove description about `dep prune`

---

docs/FAQ.md

This change adds named anchor with id attribute for anchors with "'"
character. This enables the links to work in both github and docusaurus.
Verify that the links work in both github and docusaurus. I've verified myself and they work.
No.
No, but a followup of https://github.com/golang/dep/pull/1587 . Fixing link for docusaurs resulted in broken link in github markdown preview.

FAQ: fix anchors with "'" in github and docusaurus

---

cmd/dep/status.go

We no longer have -detailed flag. Remove it from status help. A similar paragraph for
project status would be added later for #1367 .
Nothing. Just a cleanup.
No.
None.

status: remove -detailed flag from help

---

docs/FAQ.md

the link “How do I constrain a transitive dependency’s version” points to https://golang.github.io/dep/docs/FAQ.html#how-do-i-constrain-a-transitive-dependencys-version, should be https://golang.github.io/dep/docs/FAQ.html#how-do-i-constrain-a-transitive-dependency-s-version (dash after “depedency”)

docs/FAQ.md: fix typo in relative URL 

---

cmd/dep/prune.go

Adds the doc link to how to add prune config to Gopkg.toml and fixes typo.
fixes #1579

Amend prune command line message to include doc link

---

docs/daily-dep.md
docs/deduction.md
docs/failure-modes.md
docs/the-solver.md

Use of the lowercased name (gopkg.toml.md) was resulting in 404s.

Fix case of Gopkg.toml.md links in the docs

---

cmd/dep/ensure.go

```
Either import/require packages from these projects so that they become direct
dependencies, or convert each [[constraint]] to an [[override]] to enforce rules
on these projects, if they happen to be transitive dependencies,
```
This should end with a full stop instead of a comma.
This is just a copy change so shouldn't be anything significant to watch out for.
N/A

Fix innefective constraints message.

---

docs/FAQ.md
gps/bridge.go
gps/doc.go
gps/lock.go
gps/lockdiff.go
gps/version.go

This PR improves and adds `package gps` documentation, based on scanning through the [godoc](https://godoc.org/github.com/golang/dep/gps).
- More/better info to add.
- Were any of the sentences I punctuated cut off?
Should links to https://github.com/sdboyer/gps/wiki be forwarded elsewhere? Or is that still the best resource?
Towards #672.

gps: improve documentation; add package doc

---

cmd/dep/ensure.go
cmd/dep/init.go
cmd/dep/prune.go
gps/example.go
gps/prune.go
gps/prune_test.go
gps/solution.go
gps/solution_test.go
txn_writer.go
txn_writer_test.go

This PR proposes making some exported API surrounding logging more flexible.  The effect is simpler caller code (e.g. `nil` rather than `discardLogger`), and completely removing some "log" imports from gps.
gps:
- PruneProject: remove unused logger
- WriteDepTree: swap logger for onWrite callback
- fix example
dep:
- SafeWriter.Write: nilable logger
cmd:
- ensure/prune/init: react to changes
Is there a better name for `gps.WriteProgress`?
Towards #672.

log.Logger api changes

---

testdata/txn_writer/expected_manifest.toml
txn_writer.go

Refer to new docs instead of GitHub in `Gopkg.toml` example.
I think that it is better to have new docs than GitHub to refer to docs.
Whether the link destination is correct or not
No.
None.

Refer to new docs instead of GitHub in `Gopkg.toml` example

---

docs/daily-dep.md

`dep` used to have documentation showing how to generate nifty dependency graphs from dep status but they got lost in the great doc shuffle of 2018.This PR adds these docs to the new website.
- Is the section placed at the right position in docs ?
- Any more information to add ?
- Does the addition render correctly in website ?
Fixes #1663

Added lost documentation about generating graph visualizations

---

.travis.yml
Makefile

* `make get-deps` installs the tools used to validate dep, e.g. golint
* `make` runs a sane set of defaults that mimic what a PR does without adding too much burden. Doesn't do the code coverage checks because I'm not sure anyone cares... :trollface: 
* `make build` - format and compile dep binary for the current GOOS/GOARCH
* `make test` - run the tests
* `make validate` - run all the static analysis, linting, etc
* `make docusaurus` - builds and runs the site in a docker container because I refuse to install npm on my machine
* `make install` - compiles and installs dep

Make it easier for contributors to mimic a PR

---

docs/FAQ.md

When we migrated to our new doc site we lost the following topic:
- [testing- changes-to-a-dependency](https://github.com/golang/dep/tree/e69d6e84581e1b9944bb38e2fa150ce18a850ba5#testing-changes-to-a-dependency)
- [changing-dependencies](https://github.com/golang/dep/tree/e69d6e84581e1b9944bb38e2fa150ce18a850ba5#changing-dependencies)
This PR attemts to add these back to the new docs website. 
- Is the section placed at the right position in docs ?
- Any additional information missing ?
Fixes #1665

Added two lost docs Testing changes to a dependency, Changing dependencies

---

internal/importers/godep/importer.go
internal/importers/godep/importer_test.go
internal/importers/importertest/testcase.go

In a godep manifest, entries in Packages are commonly used to specify extra
dependencies of a project, like tools (code generators for example).
Adding those same packages to dep's "required" entry achieves the same.
This hopefully reduces the number of manual tweaks to Gopkg.toml before a migration is "complete".

godep: Import additional packages as required

---

.travis.yml
CHANGELOG.md
appveyor.yml

This PR increments the go versions for Travis and AppVeyor.  1.10 is only on release candidate 1, but is expected this month.  I don't know if Travis/Gimme will route `1.10.x` to `1.10rc1`, but in case it does and this turns green: **Don't merge until 1.10 is officially released!**.

increment CI go versions from 1.8.x/1.9.x/tip to 1.9.x/1.10.x/tip

---

CHANGELOG.md
README.md
install.sh

Provides a portable sh script for installing an appropriate dep binary into your environment.
Some regular build environments need `dep` installed but don't want to pull all the dependencies and build it every time. (Especially in docker-based build environments). 
This script provides an easy way to install dep into the GOPATH/bin or specified location via:
```
$ curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
```
It _should_ be compatible with basic `sh` syntax without needing any `bash` magic. I'd appreciate it if others could test it in their environments.
It supports both `curl` and `wget` as download mechanisms and bails out if neither are available.
It supports the current binaries available under releases.
- Is this something dep actually needs? 
- Should …

Install.sh script for dep

---

docs/Gopkg.toml.md

The default prune settings have changed, but the docs have not been updated.
N/A
No
This PR updates the docs for the following PR: https://github.com/golang/dep/pull/1460

Update docs to reflect default prune settings

---

gps/solution_test.go

This PR *"fixes"* a nil pointer benchmark panic by calling `Fatalf` instead of `Errorf` to halt the test.  The underlying failure to create a `SourceMgr` still exists.
> failed to create SourceManager: "failed to ensure directory at \"/tmp/vsolvtest/cache/sources\": mkdir /tmp/vsolvtest/cache/sources: no such file or directory"
Is the root cause obvious enough to fix in this PR? Or is there some local state to initialize first which can be documented?
In general, should we run benchmarks in CI, if only to confirm that they work? Or would it be a mistake to have code which is only covered by benchmarks and not separate tests in the first place?
(FYI - There are only four benchmarks, and two are hard coded to skip)

gps: BenchmarkCreateVendorTree - fatal error instead of nil panic

---

cmd/dep/root_analyzer.go
internal/feedback/feedback.go
internal/feedback/feedback_test.go

This is pass at #908 , which intends to inform users when changes have been made from their imported revisions.
In addition to giving the user feedback, this PR changes the implementation of:https://github.com/golang/dep/blob/a92678159ec741a4d28f4b2ea4727de1156ab823/cmd/dep/root_analyzer.go#L167 
to use a map of the projects in the old lock in order to:
a. Find projects that exist in the new and old locks for diffing
b. Find projects that are only in the new lock for `NewLockedProjectFeedback`
Am I even on the right track? I may be misunderstanding the differences b/w locks, constraints, and manifest (the terms are a bit fuzzy as yet) or what I'm actually to compare to see a change.
- Am I looking at the right data to check if a pertinent change has happened?
- Is the `Feedback` pattern …

Note diffs b/w imported and solved lock

---

.travis.yml
README.md

Test using `1.10.x` since gimme has been updated: https://github.com/travis-ci/gimme/pull/130
Updates the minimum in the docs.

change CI to 1.10.x; update docs

---

CHANGELOG.md
gps/deduce.go
gps/deduce_test.go
gps/error.go
gps/manager_test.go
gps/maybe_source.go
gps/maybe_source_test.go
gps/pkgtree/pkgtree.go
gps/pkgtree/pkgtree_test.go
gps/source.go
gps/source_cache.go
gps/source_cache_bolt.go
gps/source_cache_bolt_encode.go
gps/source_cache_bolt_test.go
gps/source_cache_multi.go
gps/source_cache_test.go
gps/source_manager.go
gps/source_test.go
gps/vcs_repo.go
gps/vcs_repo_test.go
gps/vcs_source.go
gps/vcs_source_test.go

This PR contains a set of changes primarily motivated by making sourceGateway state transitions more fine grained and special cases explicit, so that the persistent cache can be fully leveraged when integrated.  From the changelog:
> Reduce network access by trusting local source information and only pulling from upstream when necessary
~Should a note be added to the `CHANGELOG`?~ Did this.
Toward #431
Fixes #415

gps: fine grained source transitions

---

docs/daily-dep.md

- update missing/extra articles ("a", "the")
- swap out , for ( ) where it felt appropriate to increase clarity
- moved "especially on large projects" to end of its sentence to increase clarity

modify daily-dep grammar and sentence structure

---

install.sh

Fix multiple issues when curl is not available and wget is used:
- Downloading JSON for the latest release results in HTTP 302 and wget
redirects to the new location.  Read HTTP status only from the last
line of output else the code wouldn't match 200 even if the request
was successful.
- Don't set `--content-on-error` when using wget.  It is of no
consequence since we are checking the HTTP status code and exit if the
response isn't 200 OK.
- `type` is undefined in POSIX sh, use `command` instead.
- Clean up the temp file.
Fixes #1728.

fix install script when curl is not available

---

cmd/dep/status.go
cmd/dep/status_test.go

This pul requests chages the structure of the data fed into the template used by the `go status -f` command. The BasicStatus struct had fields that were not directly of type string making certain template constructs confusing (ex. `dep status -f='{{if eq .Constraint "master"}}{{.ProjectRoot}}{{end}}'`  doesn't work because _.Constraint_ is of type gps.Constraint, not a string).
This PR takes such elements and puts them into a structure whos type is string making the above example work.
In addition, I added some documentation to the help prompt explainging the usable field names and giving an example.
Is there any other place / a better place that I should document the -f flag?
fixes #1497
fixes #1540

Dep status -f doc and string display

---

CHANGELOG.md
cmd/dep/status.go

Update Changelog for #1549 and typo fixes

---

CONTRIBUTING.md

Fix the hyperlink for CoC as hyperlink was including extra word `that`.

Fix hyperlink for CoC in contribution guide

---

gps/pkgtree/pkgtree.go

Signed-off-by: Tao Wang <twang2218@gmail.com>
`bytes.IndexByte` will return `-1` if it cannot find anything, so to check whether there is a `\n` in the comment, the condition should be `>= 0`, rather than `> 0`.
fixes #1742

Fix issue 1742 by replacing '>' with '>='

---

docs/FAQ.md

There are 2 **Gopkg.lock** without back-ticks around. So I wrapped those text with back-ticks for consistency. All others is already wrapped with back-ticks.
Just check **Gopkg.lock** text in FAQ pages
No. It is easy to review.
Broken paragraph consistency

Wrap the "Gopkg.lock" text with back-ticks

---

Makefile

Addresses golang/lint#397, which is currently causing PR builds to fail 😬.
I edited this from the browser (😬😬), so double-checking my Make syntax is right. Adapted from @carolynvs's PR: kubernetes-incubator/service-catalog#1975
Nope!
N/A

Workaround golint hosting problem.

---

docs/FAQ.md

New dep users may be confused about the lack of documentation for changing imports after adopting dep (assuming that imports would need to be relative.) This points users directly to the go documentation that explains /vendor and outlines that NOT changing import paths is normal. 
I'm a first-time dep user, so the overall accuracy should be verified.
No issue is open for this.

Add package import process to FAQ

---

install.sh

Uses the `go env GOPATH´ which has its own logic to determine default GOPATH 
Other usages of GOPATH that I have missed
Fixes #1733

Use `go env GOPATH` instead of env variable

---

install.sh

According to the current implementation, `install.sh` script doesn't support multiple directories in `GOPATH` environment variable, in this case it just throws error saying installation directory does not exist.
It should use the first entry path from `GOPATH` instead of throwing error.
fixes #1749

Add support for multiple directories in GOPATH environment variable in install.sh

---

cmd/dep/status.go
cmd/dep/status_test.go

The collectConstraints() function in status.go incorporates effective
constraints from the root projects manifest. Issue #1452.
This patch includes the collection of constraints as defined in the root projects manifest as described in issue 1452. It ensures that the to-be-included constraint is effective which means that it refers to a direct dependency of the project.
At a first glance, it might seem desirable to collect the root projects constraints also in the for loop over the constraints from its direct dependencies. However, since the to-be-iterated data types and the way how the manifest is resolved are different, imho it's cleaner to collect the constraints from the root project separately.
collectConstraints() does currently _not_ resolve the overwrite constraints from the root …

CollectConstraints from root project as well

---

gps/cmd.go

This fixes 2 classes of bugs:
- running unit tests as part of a git rebase invocation
- running dep from a repository that has a separate GIT_DIR/GIT_WORK_TREE
the location of the code might not be ideal.
fixes #1871

gps: unset some GIT_* variables for git operations

---

Makefile

This aligns the Makefile with usual practices, which differ from shell scripting.
There is no reason to run go env at variable expansion time, run it at
initialization time instead.
Also remove extra quoting for SHELL, as those are kept verbatim in the $(shell)
calls, which can lead to the attempted execution of a "/bin/bash" process
depending on the system, leading to errors like:
make: "/bin/bash": Command not found

Makefile: use simple variables

---

docs/new-project.md

Hello, first-time contributor here!
I was following along dep's tutorial right now and got stuck while trying to add new packages right before running `dep init`. It turns out I was missing creating a valid `.go` file beforehand.
After reading through some issues I found some references about the need to create a file before adding the first dependencies. When I went back to the documentation with more attention, I found the part I skipped. 
I guess most users pay more attention to the highlighted code parts than to the overall text. I know it was my mistake but one that I think might happen to more users and can easily be prevented by changing the docs a little bit. I considered changing the paragraph structure but I think that a simple emphasis in bold text is enough

Adding more emphasis to the need of create a go file before running ensure

---

internal/test/integration/testproj.go

This allows integration tests to run during git rebase operations.
Without this, GIT_DIR points to the dep repo itself, which makes git checkout
operations fail miserably.
```
$ GOCACHE=off git rebase -x "go test github.com/golang/dep/cmd/dep -run TestIntegration/ensure/add/desync" 'HEAD^'
Executing: go test github.com/golang/dep/cmd/dep -run TestIntegration/ensure/add/desync
--- FAIL: TestIntegration (0.01s)
--- FAIL: TestIntegration/ensure/add/desync (0.00s)
--- FAIL: TestIntegration/ensure/add/desync/internal (2.79s)
testcase.go:165: error raised where none was expected: 
(1/1) github.com/sdboyer/deptesttres@master
Root project is "github.com/golang/notexist"
1 transitively valid internal packages
3 external packages imported from 3 projects
(0)   ✓ select (root)
(1)	? attempt …
```

test: unset GIT_DIR for git operations in integration tests

---

CHANGELOG.md
gps/pkgtree/pkgtree.go

Fixes #1822. Talked with @sdboyer and I think its safe to remove this. Tested this on a project with an old `Godeps` folder and it solved perfectly.

Don't exclude Godeps folder. Fixes #1822

---

docs/FAQ.md

I use multiple private repos, there are only acessable via SSH and I didn't find any hint in the documentation.
Thanks @barovic and @FQ400 (#1041)

Add the git+ssh rewrite config settings

---

install.sh

This PR removes an echo statement I accidentally introduced with commit 918c75
For paper trail, this is the output on my machine when running the install.sh under cygwin
```
[DESKTOP-ARH5TT0: dep]$ sh install.sh
ARCH = amd64
OS = windows
Will install into /cygdrive/c/Users/johnl/go/bin
Fetching https://github.com/golang/dep/releases/latest..
Release Tag = v0.4.1
Fetching https://github.com/golang/dep/releases/tag/v0.4.1..
Fetching https://github.com/golang/dep/releases/download/v0.4.1/dep-windows-amd64.exe..
Setting executable permissions.
Moving executable to /cygdrive/c/Users/johnl/go/bin/dep.exe
```
No
None. But it removes a silly mistake in the fix to #1740

Removes "echo" statement introduced with commit 918c75

---

docs/env-vars.md

This PR adds `DEPCACHEAGE` env var documentation.
Related to #431

Document DEPCACHEAGE in env-vars.md

---

context.go
context_test.go
internal/fs/fs.go
internal/fs/fs_test.go

Issue: https://github.com/golang/dep/issues/1946
Host system GOPATH may contain repeated separators or other artifacts which can cause an error
when not needed. E.g:
GOPATH:
```
/home/user//.gopath
/home/user/./.gopath
/home/user/code/../.gopath
```
Error:
```
/home/user/.gopath/src/github.com/project/repo is not within a known GOPATH/src
```
The function `filepath.Clean()` is used in order to simplify filepaths and remove the artifacts.
In order to fix the issue only the changes to `internal/fs/fs.go` are required. However `context.go` is also
updated to further clean the GOPATH as it gets returned from `TestDetectGOPATH`.
Test cases were added in `context_test.go` and `internal/fs/fs_test.go`, which currently only cover repeated
slashes, since this was what the bugfix is targeting. …

Improve handling of paths containing repeated separators (fix #1946).

---

docs/installation.md
docs/uninstalling.md
website/sidebars.json

There's good docs on how to install dep, but we're missing docs on how
to uninstall dep. This adds them. I thought about adding some text to
the top-level README.md file but figured uninstalling dep wasn't a vital
topic for top-level docs and that a separate doc in the docs/ tree was
more than enough.
Issue #1953

add documentation explaining how to uninstall

---

txn_writer.go

The previous code was attempting to copy the .git directory into
vendor/vendor/.git, i.e., with an extra level of nesting. It was
then failing to notice the error because it was only reporting errors of
type *os.LinkError.
Fix the bug by removing the layer of nesting and reporting all errors.
Fix #1997.

Fix bug in preservation of vendor/.git

---

cmd/dep/init.go

Length never returns negative values.
Signed-off-by: Iskander Sharipov <quasilyte@gmail.com>

cmd/dep: replace `len(x)<=0` with `len(x)==0`

---

.travis.yml
cmd/dep/dep_test.go
cmd/dep/status.go
gps/pkgtree/pkgtree.go
hack/coverage.bash
hack/test.bash
internal/fs/fs.go

Normally I would submit these all as separate PR's however they are all necessary to merge together because we can't merge anything unless the build is green.
A summary of changes:
- Run the big tests/linters on Go 1.11 not Go 1.10.
- Fix several errors reported by the linter.
- Exit 0 if `go test -race` fails (it fails)
- fix Mercurial command hang by adding bitbucket.org to known hosts list.

Build back to green (hopefully)

---

.travis.yml

Previously we declared &simple-test twice, instead declare it once and
load it multiple times.

.travis.yml: only one YAML declaration

---

docs/migrating.md

Grammar in docs only PR
Note: I also inserted the word "be" in another PR please note that this is a new instance of an omission of the same word

Grammar and missing word fixes

---

cmd/dep/status_test.go
gps/verify/lockdiff.go
internal/fs/fs_test.go

Gofmt in Go 1.11 beta 2 handles struct alignment differently, as
demonstrated in this diff. Running "make test" makes these same
whitespace changes to the files in question.
Without this change, running "make test" on tip will consistently generate Git
diffs.

Run latest gofmt on project

---

.codeclimate.yml

The go fmt recommendation from Code Climate does not line up with the
go fmt recommendation on tip. Ignore it.

codeclimate.yml: disable go fmt check

---

.travis.yml

Older Ubuntus cause Mercurial connections to fail with this error:
Error on cloning hg repo: unable to get repository: warning:
connecting to bitbucket.org using legacy security technology (TLS
1.0); see https://mercurial-scm.org/wiki/SecureConnections for more
info
(using CA certificates from /etc/ssl/certs/ca-certificates.crt; if you
see this message, your Mercurial install is not properly configured;
see https://mercurial-scm.org/wiki/SecureConnections for how to
configure Mercurial to avoid this message)
Per
https://travis-ci.community/t/travis-ci-linux-build-environments-cant-clone-from-bitbucket-anymore-mercurial/1182/3,
the recommendation is to upgrade to Xenial, which has either a newer
Mercurial, a newer Python, a newer OpenSSL or some combination of
those.
Updates #2071.
Updates …

travis.yml: upgrade to Xenial

---

Gopkg.lock
gps/cmd_unix.go

Previously, if dep tried to clone a repository over ssh that contained
zero padded file modes, dep would fail to clone and then hang. You can
reproduce this failure with the following .gitconfig:
[url "git@github.com:"]
insteadOf = https://github.com/
[transfer]
fsckobjects = true
[fetch]
fsckobjects = true
[receive]
fsckobjects = true
and the following Gopkg.toml. (It is not my intention to single out
this project - I searched Github for Go projects with zero padded file
mode errors, and found this one.)
[[constraint]]
name = "github.com/remogatto/gospeccy"
branch = "master"
`dep ensure` hangs because the git clone operation spins up an `ssh`
process as a child process. `cmd.Process.Kill` kills the parent `git`
operation, but not the child `ssh` operation, so it's orphaned and we
don't …

gps: return error if 'git fsck' checks are enabled and repo is corrupt

---

.travis.yml
hack/build-all.bash
install.sh

Updates #2062. 
Users have requested releases that use the s390x architecture

install.sh: add s390x to the install script

---

.travis.yml
hack/build-all.bash
install.sh

On path to close #1807 on [oauth2_proxy arm support](https://github.com/pusher/oauth2_proxy/issues/16)
Tested:
- Building armv6 and arm64 binaries on amd64
- Running arm binaries
- Using armv6 binary on RPi 3B to build another project [oauth2_proxy](https://github.com/kskewes/oauth2_proxy/tree/build)
(`dep ensure`)
Not verified:
- Install script completes as binaries not published, looks okay
though.
- `hack/test.bash` - must have missed something.
armv6 (RPi 3B):
```
karl@pi1:~/go/src/github.com/pusher/oauth2_proxy $ dep version
dep:
version     : v0.5.0-31-g73b3afef-dirty
build date  : 2019-02-01
git hash    : 73b3afef
go version  : go1.11.5
go compiler : gc
platform    : linux/arm
features    : ImportDuringSolve=false
karl@pi1:~/go/src/github.com/pusher/oauth2_proxy $ make dep
dep …
```

feat(arm): Add build and install support for armv6 and arm64

---

gps/metrics.go
gps/selection.go
gps/trace.go

Simplify `x += 1` further to `x++`.
Already open as #2028 but the fork doesn't exist anymore and I can't push changes to it.
Originally submitted by @quasilyte

gps: simplify `x = x <op> y` to `x <op>= y`

---

CHANGELOG.md

I think it would be a good idea to do a release! I've added the latest commits to the CHANGELOG.
If there are more things we should merge then we can do another release shortly after this one. We need to start getting in the habit though.

CHANGELOG: prepare for 0.5.1 release

---

.travis.yml

In January, #2102 was closed with 5ae9d8b to build ARMv6/7 binaries.
This seems to be working, but there are no release files uploaded to
Github for this architecture, because the wrong filenames are used in
.travis-ci. This PR fixes that.
It must be noted that the dep install script is already modified to
expect a ARMv6/7 binary in the Github releases, so it errors out on
404 instead of emitting a clear error message which it did before:
```
Fetching https://github.com/golang/dep/releases/download/v0.5.1/dep-linux-arm
Request failed with code 404
```
Originally submitted by Github user confiks as #2135.

travis.yml: Use correct filenames for arm (v6/7) release files

---

Gopkg.toml

This PR is a follow up from 6dfe5e25f0c3444a2be3637377b28e98899c4765 to set the locked https://github.com/pelletier/go-toml version in the `Gopkg.toml`.

upgrade toml import

---

gps/discovery.go

Apply the same change as in [golang.org/cl/175219](https://golang.org/cl/175219) to this copy of the
`parseMetaGoImports` function, helping keep them in sync.
The "mod" type is not a real version control system (VCS), it applies
only when in module mode. Skip it and continue to consider only real
VCS types.
This resolves `parseMetaGoImports` returning a "multiple meta tags match
import path" error on packages that offer `go-import` meta tags with both
a true VCS and the "mod" type.
Reference: https://golang.org/cmd/go/#hdr-Remote_import_paths
Fixes #2151

gps: ignore "mod" VCS type in parseMetaGoImports

---

Makefile
gps/deduce.go
hack/lint.bash

This enables support for private gitlab files and other places where
the URL requires basic authentication.
The idea and the large majority of the implementation comes from @wesgur.
Fixes #2061.
Fixes #1898.

gps: support loading credentials from a netrc file

---

CHANGELOG.md

CHANGELOG: prepare for 0.5.2 release

---

hack/lint.bash
internal/test/test.go

The most recent version of staticcheck drops the "--ignore" flag in
favor of inline ignore directives, so we need to use those or fix on
the older version.
Good news is two of our ignore directives are now no longer needed.
Updates dominikh/go-tools#514.
Updates dominikh/go-tools#515.
Fixes #2178.

hack,internal: fix staticcheck

---

docs/Gopkg.toml.md

Previously the provided Gopkg.toml is not valid. Thanks @liurui-1 for
spotting the error.
Fixes #2174.

docs/Gopkg.toml.md: fix toml example

---

gps/vcs_repo.go

Previously, the "-x" in
git submodule foreach --recursive git clean -x
was being applied to the "git submodule" command not the "git clean"
command. git submodule foreach expects the inner command to be wrapped
in a single string, so pass git clean as a single string.
Verified this works as expected on the command line.
Fixes #2164.
Fixes #2168.

gps: pass correct arguments to "git clean"

---

cmd/dep/status.go

Hi!  This minor typo was caught by the Lintian tool as part of routine Debian packaging task while upgrading to 0.5.4:
```
$ lintian
I: go-dep: spelling-error-in-binary usr/bin/dep formating formatting
```
Many thanks!

Fix minor typo (caught by Lintian)

---

README.md

This change amends the initial README section to make it clear that
- the Go project has officially adopted modules as the way to manage dependencies in Go;
- the Module System is no longer a prototype, and it's ready for production use.
Fixes  golang/go#35894

README: clarify current status of Go dependency management
